### ISSUE TITLE
doesn't match vsan resyrn value.

### ISSUE THREAD

**Issue by trungtien** [sexibytes/sexigraf#101]
Hi team,

Vsan resyrn value on sexigraf doesn't match with vsan resyrn on vcenter.

![b](https://cloud.githubusercontent.com/assets/16741935/23546780/bcf30e84-0033-11e7-8c99-8dffb9830d2b.png)
![a](https://cloud.githubusercontent.com/assets/16741935/23546782/c01744d6-0033-11e7-9774-b4ad58a39f6b.png)

Any help would be appriciated.

**Comment by rschitz** [comment]
This is GB vs GiB i guess
