### ISSUE TITLE
Please add AD/LDAP authentication support

### ISSUE THREAD

**Issue by tom551** [sexibytes/sexigraf#103]
Hi, please add AD/LDAP authentication support for to the Webinterface. If possible please directly in the web UI without the need of touching config scripts.

Thanks!

**Comment by vmdude** [comment]
Grafana support AD/LDAP authentication by default, but we cannot set it up as all AD configuration depends on client platform.
Please refer to http://docs.grafana.org/installation/ldap/ if you want to enable AD/LDAP authantication on your appliance
