### ISSUE TITLE
How to get disk health status?

### ISSUE THREAD

**Issue by trungtien** [sexibytes/sexigraf#105]
Hi team,

I need to get physical disk health status. Can you help me to get this metric?
![untitled](https://cloud.githubusercontent.com/assets/16741935/24203898/82a8bc90-0f49-11e7-8526-dc84aa657f88.png)

**Comment by rschitz** [comment]
it may be possible with the 6.5 SDK

**Comment by rschitz** [comment]
https://www.virtuallyghetto.com/2017/04/smart-drive-data-now-available-using-vsan-management-6-6-api.html

"although this API was added under the vSAN Management API, you do not actually have to be using vSAN to be able to use this new API"
