### ISSUE TITLE
[Request] Containerizing

### ISSUE THREAD

**Issue by rockaut** [sexibytes/sexigraf#106]
Hello there,

have you thought of trying to containerize your app (not just put it in one container, do it right and split the workload)? If not, would you mind if i fork and try it?

I like your solution but in the last months we use containers more and more and from our experience it work extremely well. Especially as it would be easily possible to deploy sexigraf to baremetal as well.

Best regards

**Comment by rschitz** [comment]
https://github.com/sexibytes/packer-sexigraf
