### ISSUE TITLE
Datacenter names with ÅÄÖ will cause problems

### ISSUE THREAD

**Issue by apaulsson** [sexibytes/sexigraf#114]
Hi,

We had datacenter names with ÅÄÖ in them, and that made some issues.. We often got HTTP 500 errors when trying to select DCs and clusters:
root@sexigraf:/var/lib/graphite/whisper/vmw/vc01_vmware_local# ls -al
total 28
drwxr-xr-x  7 _graphite _graphite 4096 Jul  5 12:46 .
drwxr-xr-x  7 _graphite _graphite 4096 Jun  8 12:10 ..
drwxr-xr-x 13 _graphite _graphite 4096 Feb 14 16:36 metrokluster
drwxr-xr-x  3 _graphite _graphite 4096 Jul  5 12:46 raus_dc
drwxr-xr-x  3 _graphite _graphite 4096 Feb 14 16:36 raus_g?rd
drwxr-xr-x  3 _graphite _graphite 4096 Jun 14 12:41 rausg?rd_dc
drwxr-xr-x  3 _graphite _graphite 4096 Jun 14 12:41 s1_dc

The built in house cleaner showed those folders with empty names, and were unable to delete them. Had to manually delete them via ssh in order to get things to properly work again.

**Comment by rschitz** [comment]
Hi, thanks for your comment. We fixed that issue (https://github.com/sexibytes/sexigraf/issues/89) and it will be available in the soon to be released next version.
