### ISSUE TITLE
SexiGraf House Cleaner not working anymore

### ISSUE THREAD

**Issue by Benji-C** [sexibytes/sexigraf#125]
Hello,

Since the latest version 0.99d, the house cleaner in the webadmin isn't working anymore.
You cannot browse the tree when in the house cleaner - only the top level folder can be selected (carbon, collectd, esx, vi, vmw).

We decommissioned couple of ESX and we need to clean the data under the esx folder.

Thanks in advance,
Benji.

**Comment by vmdude** [comment]
A previous issue has been created and fixed for this, see #120
