### ISSUE TITLE
Dashboard not working on a mix environment

### ISSUE THREAD

**Issue by Benji-C** [sexibytes/sexigraf#129]
Hello,

I'm using sexigraf 0.99c, vCenter 6.5 and i have a mix environment with Cluster and non-Cluster servers.
Because of that i can't run some query when i need to sum up Cluster and non-cluster values.

Example: i created the basic following query that count the number of ESX in a datacenter:
#A - countSeries(esx.*.*$Department*.*.quickstats.overallStatus)
#B -  countSeries(vmw.*.*$Department*.*.esx.*.quickstats.overallStatus)
#C - sumSeries(#A,#B)

I templated $Department with custom values that can be found in the datacenter name.
If my datacenter contain only Cluster environment OR non-cluster environment, the query fails because #A or #B is null. 
If my datacenter contain a mix of both, then it's working.

I've tried everything to not count if series #A or #B is null with remove*Value, transformNull. I've tried setting a value mapping of 1 if value is null, and then using useSeriesAbove with 0.

The same issue can be reproduced in the default Flambx dashboard, in the template values if you select an ESX outside a cluster, then the singlestat "# ESXi" or "# VMs" won't update (because the query is only with vmw).

Please advice if you can help me build a query that would fix the issue or if it's a bug.

Thanks in advance,
Benjamin.

**Comment by rschitz** [comment]
graphite 0.9 bug
