### ISSUE TITLE
ViPullStatistics.pl - Illegal division by zero

### ISSUE THREAD

**Issue by srnlfk** [sexibytes/sexigraf#132]
/ViPullStatistics.pl line142 - DIE Illegal division by zero at /opt/vipull/ViPullStatistics.pl line 142

**Comment by rschitz** [comment]
can you provides logs?

**Comment by srnlfk** [comment]
[ViPullStatistics.txt](https://github.com/sexibytes/sexigraf/files/2068087/ViPullStatistics.txt)

**Comment by rschitz** [comment]
it looks like the perfmanager don't return any values for a particular query, could you  try to replace this file https://github.com/sexibytes/sexigraf/blob/dev/root/ViPullStatistics.pl in the /root folder of the SexiGraf appliance?
