### ISSUE TITLE
regenerate ssh keys at first start up

### ISSUE THREAD

**Issue by rschitz** [sexibytes/sexigraf#139]
it would be a thing to regenerate ssh keys for security reasons at first boot of a freshly deployed appliance

**Comment by rschitz** [comment]
```
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server
systemctl restart ssh
```

**Comment by tsborland** [comment]
Could easily create an init script, and disable it once the first boot has concluded.

Create file /etc/init.d/99-sexigraf-firstboot.sh:
```
#!/bin/bash

/bin/rm /etc/ssh/ssh_host_*

/usr/sbin/dpkg-reconfigure

/bin/systemctl restart ssh

/usr/sbin/update-rc.d 99-sexigraf-firstboot.sh disable
```

Make sure the ownership is correct:
`chmod 755 /etc/init.d/99-sexigraf-firstboot.sh`

Enable the script prior to packaging OVF:
`update-rc.d 99-sexigraf-firstboot.sh defaults`
