### ISSUE TITLE
Please make HTTPS/SSL as a default for the 0.99e version 

### ISSUE THREAD

**Issue by lejoy23** [sexibytes/sexigraf#146]
Due to security terms it would be very nice to have SSL as a default for the Apache2 Service/Graphite and Grafana Services. I appreciate your work very much - please continue you with that awesome stuff!

Thanks to Raphael for the very fast reply!

**Comment by rschitz** [comment]
Hi, thanks for your support.
we'll first add a self-signed cert on the apache reverse proxy and add a simple way to change the certificate in the web admin page in a future release.
