### ISSUE TITLE
Veeam Backup Integration

### ISSUE THREAD

**Issue by lejoy23** [sexibytes/sexigraf#147]
Hi there,
As many SexiGraf Users are using Veeam Backup as their main backup infrastructure it could be a good feature to have Dashboards for Veeam integrated in the Sexigraf Appliance as an optional Task.

Thanks in advance.

**Comment by rschitz** [comment]
Hi, thanks for your support.
we'd love that and we're trying to find something cooler than what [we did in SexiLog](http://www.sexilog.fr/sexiboards/veeam-backup/)
Stay tunned!

**Comment by rschitz** [comment]
https://community.veeam.com/blogs-and-podcasts-57/vbr-v11-restful-api-for-vbr-415
https://github.com/VeeamHub/veeam-postman/tree/master/postman_for_veeam_backup_and_replication

**Comment by rschitz** [comment]
![image](https://github.com/sexibytes/sexigraf/assets/8385646/9646df10-96e0-485b-8c30-cf617871d9ff)

**Comment by rschitz** [comment]
https://www.veeam.com/veeam_backup_12_0_rest_api_reference_map_ot.pdf

**Comment by rschitz** [comment]
![image](https://github.com/sexibytes/sexigraf/assets/8385646/d10ef3c9-6a4e-4faa-866e-f1726ac130df)
