### ISSUE TITLE
VsanPullStatistics.pl line 408 - DIE Illegal division by zero at /root/VsanPullStatistics.pl line 408

### ISSUE THREAD

**Issue by knolan1** [sexibytes/sexigraf#160]
0.99e (08/2018 White Forest release)
Running VSAN 6.5 U1 (VSphere 6.5 U1)
Running VCenter 6.5U2

Inspired by the previous issue submited about VIPullStatistic #132 
I could if needed provided log with a certain anonymity.

Thanks for your work so far,

**Comment by rschitz** [comment]
It looks like one of your SSD capacity is not populated
Could you try this version https://github.com/sexibytes/sexigraf/blob/09c10e17a5dcf08a6dfc6295f7e9313b620bc880/root/VsanPullStatistics.pl

**Comment by knolan1** [comment]
Hello, 

Thanks for your update, i'll gather further intel, and tell you about.

Regards,

**Comment by Roudiroudi** [comment]
Hello,

When try the new version attached to the link you mentioned , collection is not starting and logs are empty with no messages.In the pullexectime graff i don't see anymore yellow point corrresponding to vsan collection statistics.If i put back the previous file it works again , pull is processing but still got the same error. Is ther a conf missing somewhere when i replace the file with the new one, i mean do i have to modify something before copying your file in the opt/root folder ? thank you for your heelp it s pretty much appreciated.

Rich

**Comment by rschitz** [comment]
try copy/paste the code in the existing file to avoid permissions issues
