### ISSUE TITLE
VMware Multi Cluster Usage Dashboard (missing resource)

### ISSUE THREAD

**Issue by mmoran23** [sexibytes/sexigraf#162]
Love this dashboard, but hate the fact I cant tell which resource is the offending consumer. Anyway to modify that dashboard to show CPU is 78% as opposed to just 78% and then me changing dasjboards to see which  resource is the offender?

**Comment by rschitz** [comment]
cross confirm with Cluster FullStats dashboard would be the simpler way

**Comment by mmoran23** [comment]
Not sure what that means? I wanted to use the heat map to quickly ID issues
in my clusters, 100's of them.

**Comment by rschitz** [comment]
it's always the memory ;)

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/issues/222
