### ISSUE TITLE
vCSA 6.7 Update 1 - DIE Can't call method "apiType" on an undefined value at /root/VsanPullStatistics.pl line 136.

### ISSUE THREAD

**Issue by johskar** [sexibytes/sexigraf#165]
Seems vSAN statistics is broken against vCSA 6.7 Update 1....
Stopped getting vSAN stats after update of vCSA from 6.7 to 6.7 Update 1, and '_/var/log/sexigraf/VsanDisksPullStatistics.log_' is showing a lot of the following error:
_DIE Can't call method "apiType" on an undefined value at /root/VsanPullStatistics.pl line 136._

**Comment by rschitz** [comment]
oups...

**Comment by kamilnew** [comment]
to fix it copy files from new version of vSAN Management SDK for Perl 6.7.1 to /root
VIM25VsanmgmtRuntime.pm
VIM25VsanmgmtStub.pm

https://code.vmware.com/web/sdk/6.7.1/vsan-perl

**Comment by rschitz** [comment]
Or wait for the packaged fix ;)

**Comment by rschitz** [comment]
@kamilnew thanks for your support by the way ;)

**Comment by rschitz** [comment]
We can confirm non regression on previous version, so this is the correct fix. Thx again kamilnew.

**Comment by johskar** [comment]
Thanks!
That fix from @kamilnew works like a charm.

**Comment by rschitz** [comment]
http://www.sexigraf.fr/vsan-dashboards-empty-after-vsphere-6-7u1-update/
