### ISSUE TITLE
Time sync for appliance

### ISSUE THREAD

**Issue by acederlund** [sexibytes/sexigraf#173]
It would be great if there was a NTP server (in client mode) installed in the appliance, or if there already is a NTP server enabled in newer appliances it would be great if the update packages could install it so the server will have correct time.

**Comment by rschitz** [comment]
We prefer to rely on VMware Tools periodic time synchronization (1min by default) since it would be necessary to add a way to edit the ntp settings to suit everyone. Is ESX/Guest sync not enough for you?

**Comment by apaulsson** [comment]
Yes, that would also be an option, did not think of it (it's not enabled per default, at least not on the appliance version we deployed).
Our deployed appliance has this setting:
Synchronize guest time with host = disabled

I think it was version 0.99b1 “Xen” that we deployed and have continuously upgraded to the latest version. Not sure if this is the case in the current OVA, will investigate this now.

**Comment by acederlund** [comment]
I just downloaded the appliance, and can confirm that the appliance does not sync time with the host per default:
      <vmw:Config ovf:required="false" vmw:key="tools.syncTimeWithHost" vmw:value="false"/>

I would suggest changing this to true in a future release, so that time sync happens automatically.

**Comment by rschitz** [comment]
indeed, thanks a lot for pointing this out

**Comment by rschitz** [comment]
The future version will require a new appliance using our import/export feature so it will solve the problem.
