### ISSUE TITLE
Alerts not working

### ISSUE THREAD

**Issue by royalliege** [sexibytes/sexigraf#175]
Grafana's Alerting feature is having no data for multiple series dashboards, no data returns for any time interval like (1h,now-5m), (5m,now). 

Test Rule
result
firing false
state ok
conditionEvals false = false
timeMs 14.782ms
logs
0
message Condition[0]: Query Result
data
1
message Condition: Eval: false, Query Returned No Series (reduced to null/no value)
data null

**Comment by rschitz** [comment]
Alerting is not supported yet by grafana on templated dashboards
http://docs.grafana.org/alerting/rules/
"The query used in an alert rule cannot contain any template variables"
