### ISSUE TITLE
Kindly Add Virtual Disk matrics

### ISSUE THREAD

**Issue by Laliteus** [sexibytes/sexigraf#180]
Hi Sir,
Kindly add virtual disk metrics support.

numberReadAveraged_number_average
numberReadAveraged_number_average
numberWriteAveraged_number_average
read_kiloBytesPerSecond_average.wsp
totalReadLatency_millisecond_average
totalWriteLatency_millisecond_average
write_kiloBytesPerSecond_average

**Comment by rschitz** [comment]
Hi, we would add I/O avg (read/write aggregated) but the other we already do but aggregated, it would be too much metrics at high scale otherwise

**Comment by rschitz** [comment]
that would be disk. commandsAveraged. average vm metric

**Comment by Laliteus** [comment]
Thank you Sir.

**Comment by rschitz** [comment]
Thank YOU for your support.

**Comment by rschitz** [comment]
aggregated virtualdisk metrics would be better because a lot of vm lack of disk.usage metric for some reason

**Comment by rschitz** [comment]
dup #182
