### ISSUE TITLE
Issues with VSAN Capacity and API version 6.7.1

### ISSUE THREAD

**Issue by adestis-mb** [sexibytes/sexigraf#181]
Hello all,

we are using script version 0.9.181 of Sexigraf.
Our vSphere environment is running on 6.7 Update 1.
The capacity information is not working anymore since we updated from 6.5 to 6.7.1.

In the ViPullStatistics we see the following warning:
```/root/VsanPullStatistics.pl line250 - WARN Argument "6.7.1" isn't numeric in numeric ge (>=) at /root/VsanPullStatistics.pl line 250.```

On that line in the file VsanPullStatistics.pl there is no relevant statement.
But on line 209 there is the following which seems to be related:
```if ($host_api >= 6.7) {```

I think it's not such a good idea to compare a string with a number using the greater or equal operator.
Maybe it's better using a module like https://metacpan.org/pod/Version::Compare

Regards
Markus

**Comment by rschitz** [comment]
Hi Markus,
Actually we already solved that issue but didn't updated the code yet.
Regarding the capacity information, did you applied the patch published on our website?

**Comment by adestis-mb** [comment]
Hello Raphaël,
we are always using the "update package" menu of Sexigraf.
It shows us that we are using 0.99e1 "White Forest".
But I downloaded now the zip file and I saw that at least the PullVsanStatistics.pl file is much newer.
Maybe the update functionality is not working.

I have no manually replaced the PullVsanStatistics.pl file with the one from the source bundle.

**Comment by adestis-mb** [comment]
Looks like it's not working anymore at all.
It probably requires everything to be up to date.
Is there a documentation for manually upgrading?

**Comment by adestis-mb** [comment]
A fresh installation of the .ova file from the website together with the upgrade to 0.99e1 brought me to the same status.
As workaround I have now changed the line 250 from:
```if ($host_api >= 6.7) {```
to
```if ($host_api eq '6.7' or  $host_api eq '6.7.1') {```

No errors on the VsanDisksPullStatistics.log anymore 
but there are still errors on the dashboard (VMware VSAN Capacity) about an internal server error.

Looks like VSAN capacity is completely broken..

**Comment by rschitz** [comment]
Hi Markus, could you try this version of the script please? https://github.com/sexibytes/sexigraf/blob/dev/root/VsanPullStatistics.pl

**Comment by adestis-mb** [comment]
Really great, it's working again.

Thank you very much

**Comment by rschitz** [comment]
Thank YOU for your support ;)
