### ISSUE TITLE
VMware_Multi_Cluster_Top_N_VM_Stats no Datapoint for disk usage

### ISSUE THREAD

**Issue by pottyfr** [sexibytes/sexigraf#182]
Hi There, 
first of all, thank you very much for your awesome work!

I´ve ran into an issue with the VMware_Multi_Cluster_Top_N_VM_Stats Dashboard. There is no graphing for the disk usage. I could no figure out what causes this issue.

Is there a need to customize the PerfCounter collection i vSphere to get this working?

Best Regards, 

Philipp

**Comment by rschitz** [comment]
Hi and thanks for your support. Are the VM running on a vSAN datastore?

**Comment by pottyfr** [comment]
Hi,
no the VM runs on a NFS Datastore. 

Cheers!

**Comment by rschitz** [comment]
I already witnessed this but never understood the cause. what's the ESX version?

**Comment by pottyfr** [comment]
We are running VMware ESXi, 6.5.0, 11925212

**Comment by rschitz** [comment]
same as #180

**Comment by rschitz** [comment]
can't do anything about it, maybe a bug or a specific case like the lack of datastore latency metric for vSAN

**Comment by rschitz** [comment]
we'll try writeOIO to have an idea off storage "pressure"
