### ISSUE TITLE
files.sexigraf.fr is down

### ISSUE THREAD

**Issue by ivoronin** [sexibytes/sexigraf#183]
https://downforeveryoneorjustme.com/files.sexigraf.fr

**Comment by rschitz** [comment]
spam

**Comment by ivoronin** [comment]
@rschitz how rude. Just wanted to notify @sexibytes that part of your project's infrastructure is down. Cant download OVA's from http://www.sexigraf.fr/quickstart/.

**Comment by rschitz** [comment]
sorry, the url looks like a spam. the url is not down but maybe your're trying to download from russia?

**Comment by ivoronin** [comment]
Yes, i'm trying to download from Russia.

**Comment by rschitz** [comment]
drop me an email to plot [at] sexigraf.fr i'll send you a dropbox link

**Comment by ivoronin** [comment]
Thanks!
