### ISSUE TITLE
Update VI pull stats frequence

### ISSUE THREAD

**Issue by Torrent007** [sexibytes/sexigraf#184]
Hi guys !

I'm very new on Sexigraf and I'm looking for an update on VI pull freq.
My Pull exec ime is about 1min-1min10
I found about `/etc/cron.d/vi_*` files and try to change `*/5 [...]` to `*/2 [...]` with a cron service restart but frequency appears to not be updated.
I also tried to reboot appliance with no success.

I'm not friendly with perl syntax and it's hard for me to understand vi pull stats workflow.

Anyone can help me to do this update ?

Thanks a lot !

**Comment by sexibytes** [comment]
Hi,

You can’t do that since we configured graphite for a 5min granularity, sorry.
Only vSAN is 1min

**Comment by Torrent007** [comment]
Thanks to your quick answer dude.
Maybe it's possible to reconfigure graphite too ?

**Comment by rschitz** [comment]
We designed sexigraf dashboards so that the 5min granularity only last for few hours, it’s averaged after that to higher ranges so I wouldn’t be very useful.
