### ISSUE TITLE
No datapoints in VMware vCenter Bad Events

### ISSUE THREAD

**Issue by escapenguin** [sexibytes/sexigraf#189]
Running a fresh 99f appliance and noticed this isn't populating. I fixed some ownership issues on the json files and gave the sexi user I created more permissions in vCenter, but still can't seem to get it to work. Not sure where else I should look. Other than that, thanks for the awesome appliance. Still using sexilog for spotting anomalies quickly to this day.

**Comment by rschitz** [comment]
Hi, could you please try an elevated user against vcenter?

**Comment by escapenguin** [comment]
I gave it admin to test and still nothing. It looks like the whisper files for the queries in the json don't exist. I purged those directories with the housekeeping tool but looks like the same ones were created again.
