### ISSUE TITLE
All graphs except Home & PullExec are showing empty datapoint

### ISSUE THREAD

**Issue by NootnootDuck** [sexibytes/sexigraf#193]
Hello,

I've installed a fresh 0.99f on an education lab, and I have troubles with populating the graphs.
I'm using admin account to log to the vCenter (it's a lab!) and inventory is generated fully.

There is an "Internal Server Error" showing on many graphs, with the following stacktrace ending:
step = reduce(lcm,[s.step for s in seriesList]) TypeError: reduce() of empty sequence with no initial value

I've made a test before with the previous version (0.99e) and it was working well...
Is there anything I'm forgetting to have it working?

**Comment by rschitz** [comment]
Hi, could you post some logs please?

**Comment by NootnootDuck** [comment]
Sure, which ones do you need?

**Comment by NootnootDuck** [comment]
My bad, I've forgot to specify the VI collect.
I've enabled it and it works now!
