### ISSUE TITLE
new dashboard "VMware All ESX VM Stats

### ISSUE THREAD

**Issue by PetrPan62** [sexibytes/sexigraf#194]

**Comment by PetrPan62** [comment]
Hi,
I am looking for a dashboard for ESX Server like the dashboard "VMware All Cluster VM Stats"
Can anyone help me?
I want to see VM statistics of VMs on an ESX stand alone.
Thanks
BR
Petr

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/757add3e1ff94e986e4e7877b54614cd19c69c18
