### ISSUE TITLE
Missing esxi hosts

### ISSUE THREAD

**Issue by syngress** [sexibytes/sexigraf#195]
Hi,

Firstly thanks for a wonder product!!

When viewing all of the cluster dashboard there are all correct and working fine, however when trying to use a dashboard where you can drill down to individual hosts a lot of my hosts seems to be missing.  I only see 11 out of the 35 hosts that I have!!

This looks to be the same issue as mentioned in #131 however that was closed by the OP with no update :(

I've also seen that when looking at the whisper files I only have files for the hosts that are listed.

Is there anyway to force Sexigraf to see the missing hosts?

Cheers :)

**Comment by rschitz** [comment]
Hi, thanks for your support.
This is by design since the hosts dashboard is only here for standalone hosts that are part of a cluster. you can find some individual hosts metrics like cpu/ram and network but that's it. we made that choice to keep things fast and avoid using extra space.

**Comment by syngress** [comment]
Hi,

Issue is that I can't see the stats for an individual host, there are 2 dashboards FlambX and VMware Standalone ESX Full Stats that give the option to see individual hosts (All of our hosts are in clusters) yet on those 2 dashboards when trying to select the host, the list only has 11 hosts, and not our full 35 hosts listed.

In addition VMware Standalone ESX Full Stats dashboard never shows any stats at all :(

Thanks.

**Comment by rschitz** [comment]
when it says "standalone" it is for standalone hosts ONLY
in the 'VMware Cluster Network Usage' dashboard, do you have all of your hosts listed ?

**Comment by syngress** [comment]
Yes, they are all listed in the 'VMware Cluster Network Usage' - Understood re: the 'standalone'

So is there a way of seeing usage (CPU, Ram, etc) for individual hosts in a cluster ? :)

**Comment by rschitz** [comment]
yes, only in this one VMware Cluster Multi ESX LiteStats

**Comment by syngress** [comment]
Perfect! Thanks so much 👍

**Comment by rschitz** [comment]
you're very welcome, glad you like our work ;)
