### ISSUE TITLE
Remove access for Web admin dashboard for non admin roles

### ISSUE THREAD

**Issue by pamziaw** [sexibytes/sexigraf#204]
Today I granted access to sexigraf to support teams for them to use with the viewer role however I realised afterwards they still could see the web admin dashboard and make changes on it. I can't figure out how to remove the permissions to this in grafana or if it can be done. Could a change be made to the permissions to prevent non admin users being able to view this dashboard?

**Comment by rschitz** [comment]
you'll have to do it manually on the SexiGraf folder since it's not possible to do it in provisioning : https://grafana.com/docs/grafana/latest/permissions/dashboard_folder_permissions/

**Comment by rschitz** [comment]
https://community.grafana.com/t/provisioning-dashboards-folder-permissions/6896
