### ISSUE TITLE
Disk expand 

### ISSUE THREAD

**Issue by Kirandp6** [sexibytes/sexigraf#214]
Hi

By default the disk is 16 GB which is small size if you have many clusters  & this is not LVM too. 

 df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        16G  2.8G   12G  19% /
udev             10M     0   10M   0% /dev
tmpfs           794M  8.6M  785M   2% /run
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           397M     0  397M   0% /run/user/0

Can this be LVM Please  ?

thanks

**Comment by rschitz** [comment]
In the upcoming version, / will be lvm and whisper files will have a dedicated disk and partition so stay tuned ;)
