### ISSUE TITLE
Debian 8 - EOL

### ISSUE THREAD

**Issue by Spleeff** [sexibytes/sexigraf#218]
Hello,

Debian "Jessie" 8 is now EOL.
Is there a new version of SexiGraf planned with a newer version of Debian ?

A newer version of Grafana too ?

Thank you

**Comment by rschitz** [comment]
Hi, and thank you for your support.
A new version based on Ubuntu 16.04 LTS and Grafana 7 is almost ready to be released, stay tuned!
