### ISSUE TITLE
Incorrect path in service restart function

### ISSUE THREAD

**Issue by Sneddo** [sexibytes/sexigraf#23]
Hey, I just deployed the the SexiGraf Appliance (or "applicance" as the download link says!) and noticed that the path for collect.d is incorrect in the restart function (line 94/95).

Should be `/etc/init.d/collectd stop` (i.e. no dot)

**Comment by rschitz** [comment]
Thanks for your feedback!

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/1a24d5ca8c68b8240a9d685a79298cce6f6fac9e
