### ISSUE TITLE
Export feature failed if data bigger than 4gb

### ISSUE THREAD

**Issue by raphoun** [sexibytes/sexigraf#233]
Hello

Trying to migrate to the new version I had this issue.
Fixed by adding --allow-limited-size and -udf options in genisoimage command to make it work in exportSexiGrafBundle.sh

**Comment by rschitz** [comment]
Hi, thanks for your feedback.
that's interesting because we manage to create and iso way bigger than 4GB.
we'll give it a try and let you know

**Comment by rschitz** [comment]
File /mnt/wfs/sexigraf-dump/whisper.tgz is larger than 4GiB-1.
-allow-limited-size was not specified. There is no way do represent this file size. Aborting.

**Comment by rschitz** [comment]
just validated your way to do it, worked perfectly fine on a 5GB iso, thanks a lot for your help @raphoun
