### ISSUE TITLE
Number of hosts - no history

### ISSUE THREAD

**Issue by raphoun** [sexibytes/sexigraf#234]
Hello,

In dashboard VMware Multi Cluster Quickstat and VM Count there is a Host count graf. 

It counts the number of hosts but there is no history, if I have 20 hosts now it will says 20 hosts even 1 year ago. Maybe I am using it wrong? I need to know the evolution of our number of hosts and I can't manage to do it in your fantastic tool :) 

If I look at the query it is maybe because it just counts the OverallStatus number of occurrences, we would need to put a value 1 for each hosts or the total each day to keep history no?

**Comment by raphoun** [comment]
Hello Raphaël

I have been able to find the metric in Superstat dashboard, you added a superstats.esx.count , perfect

**Comment by rschitz** [comment]
Hi and thanks for your support!

The ESX host latest count legend is only here as a reference against the number of vms.

I was going to send you a custom dashboard for this metric but you find it before that perfect.
This metric is fairly new so if you need a bit more history, i can show you another method but that's less accurate if you had a lot of hosts addition and removal in the cluster. let me know
