### ISSUE TITLE
configure SexiGraph

### ISSUE THREAD

**Issue by yossisoffer** [sexibytes/sexigraf#236]
Hi
i following install instructions and added the vCenter but still when i open dashboard, for example, "top n VMs" i see no data collected at all.
what am i missing?

**Comment by rschitz** [comment]
Hi, did you enable VI collect?
http://www.sexigraf.fr/web-admin/#vcenter-credstore

**Comment by yossisoffer** [comment]
Now I did,
Strange, I was sure they were enabled when I configured it….
Thx for the promptly response
It is working now

**Comment by yossisoffer** [comment]
BTW,
Which graph can show me the VMs IOPS ?

From: Soffer, Yossi (DI IT IN SE OP)
Sent: Wednesday, November 25, 2020 11:50 AM
To: 'sexibytes/sexigraf' <reply@reply.github.com>
Subject: RE: [sexibytes/sexigraf] configure SexiGraph (#236)

Now I did,
Strange, I was sure they were enabled when I configured it….
Thx for the promptly response
It is working now

**Comment by rschitz** [comment]
glad you sorted this out.
we dont have an i/o graf per vm but you can use the disk usage one to have an idea of the storage activity of the vm http://www.sexigraf.fr/vsphere-sexipanels/#vsphere-top-n-vm-stats

**Comment by yossisoffer** [comment]
Thx, so last question if I may 😊
Suppose I wrote a script which provides me with the below output.
I can run it every 5 minutes.

How would it be possible for me to generate dashboard from this output?
[cid:image001.png@01D6C34D.359A2180]



Thx
yossi

**Comment by rschitz** [comment]
What metric do you need exactly?
https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.PerformanceManager.html

**Comment by yossisoffer** [comment]
I cant find the metric,
But in general the main command I run is:
get-stat -Realtime -stat 'disk.numberwrite.summation','disk.numberread.summation'

for which I already collected the data.
The question: is there a way to import the data from excel file to dashboard?

thx

**Comment by rschitz** [comment]
we'll add the I/O metric per vm
https://github.com/sexibytes/sexigraf/issues/180

**Comment by yossisoffer** [comment]
Thx a lot Raphael,
So how can I use it?
Do I need to download something?

**Comment by rschitz** [comment]
just wait that implement it ;)
