### ISSUE TITLE
ova import error

### ISSUE THREAD

**Issue by Toddehawk** [sexibytes/sexigraf#240]
Hi,

I can`t import the ova template...at the end i get:

Zeile 163: Analysieren von „tools.syncTime“ für Attribut „key“ des Elements „Config“ nicht möglich
Line 163: Analyzing "tools.syncTime" for attribute "key" of element "Config" not possible

Any hint?

**Comment by rschitz** [comment]
Hi, what's the vcenter version?

**Comment by Toddehawk** [comment]
I am on 7.0 Update 1, but Host only without vCenter.
I read version 0.99g supports it

**Comment by rschitz** [comment]
As monitoring target yes but to deploy the appliance against an esx you have to extract the ova into a folder then modify the ovf file and remove what the esx doesn't like.

I'll try to fix that in the future

**Comment by Toddehawk** [comment]
ahh, ok. I`ll try it .
Thanks !

**Comment by rschitz** [comment]
Thanks for your support, let us know when you manage to deploy it please

**Comment by Toddehawk** [comment]
Sure....it was easy :-)
only remove line 163 **<vmw:Config ovf:required="true" vmw:key="tools.syncTime" vmw:value="true"/>**
within the sexigraf.ovf.

I imported the 4 files as appliance ...and it works !

**Comment by rschitz** [comment]
Thx, I'll add the ntp address query during deploy, that'd be better i guess
