### ISSUE TITLE
Vmware ESXi 6.0/6.5 import ova error

### ISSUE THREAD

**Issue by dani-sanchez-dorado** [sexibytes/sexigraf#241]
I have detected errors importing the .ova file in my vmware ESXi 6.0 server. Afer update the server to 6.5 version, I get some very similar errors. 

When you try to import the .ova file, you get this error

> Line 163: Unable to parse 'tools.syncTime' for attribute 'key' on element 'Config'.

In vmware ESXi 6.0 you get 3 similar errors. 

The problem is that the "tools.syncTime" setting is not supported in vmware. It works well in VirtualBox. 

**Fix:**
I get the procedding to edit ova files here: https://www.virtualhome.blog/2019/11/29/how-to-modify-an-ova-appliance-file/

To resolve the problem, you have to install the VMware OVF Tool command-line utility to open the .ova file. 

First of all, decompress the .ova file: 

`
C:\Program Files\VMware\VMware OVF Tool>ovftool.exe --allowExtraConfig --skipManifestCheck  c:\Users\test\Downloads\sexigraf.ova c:\temp\sexi\sexi.ovf
Opening OVA source: c:\Users\test\Downloads\sexigraf.ova
The manifest does not validate
Opening OVF target: c:\temp\sexi\sexi.ovf
Writing OVF package: c:\temp\sexi\sexi.ovf
Transfer Completed
Warning:
 - The manifest is present but user flag causing to skip it
Completed successfully
`

Then, edit the manifest sexi.ovf file. Change the line 163

>      <vmw:Config ovf:required="true"  vmw:key="tools.syncTime" vmw:value="true"/>

to 

>       <vmw:Config ovf:required="false"  vmw:key="tools.syncTime" vmw:value="true"/>

Now, the have to pack again the .ova file. 
First, recalcule the SHA256 for the sexi.ovf  file

`
C:\Temp\sexi>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

PS C:\Temp\sexi> Get-FileHash .\sexi.ovf

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          3BC13BE59E275DFCBC6CD7DBBE7EA0B664DADF36BD7129B7899B3D50A440410B       C:\Temp\sexi\sexi.ovf

`
And now, change the CRC of sex.ovf in the manifest file: 

`
SHA256(sexi.ovf)= 3bc13be59e275dfcbc6cd7dbbe7ea0b664dadf36bd7129b7899b3d50a440410b

`

Now, repack the .ova file with: 

`
C:\Program Files\VMware\VMware OVF Tool>ovftool.exe --allowExtraConfig c:\temp\sexi\sexi.ovf c:\temp\sexi\sexi_changed.ova
Opening OVF source: c:\temp\sexi\sexi.ovf
The manifest validates
Opening OVA target: c:\temp\sexi\sexi_changed.ova
Writing OVA package: c:\temp\sexi\sexi_changed.ova
Transfer Completed
Completed successfully
`

The file sexi_changed.ova will be imported by vnwware. 

I think that the syncTime parameter is not so important to cause so problems to all the vmware community. This little change will avoid a lot of headaches to many people. 

Thanks!

**Comment by bob454522** [comment]
thank you so much for taking the time to write this detailed write up.  This also fixed the ova import issue for me (on vCenter + ESXi hosts @ 6.5u3).
i also agree with your suggestion to the dev:

> I think that the syncTime parameter is not so important to cause so problems to all the vmware community. This little change will avoid a lot of headaches to many people.

**Comment by rschitz** [comment]
Thanks guys, we'll change this setting in the next release and add an NTP address query during deployment if someone whats to override the linux default #211

**Comment by rschitz** [comment]
https://github.com/sexibytes/packer-sexigraf/commit/71ac5c4777efbf53a232ec91afa8b4c6b9d27979

**Comment by atillier** [comment]
@rschitz sorry for jumping back on this old issue. I have the same problem with latest version 0.99g and ESXi 7.0 U3. Was it fixed with https://github.com/sexibytes/packer-sexigraf/commit/71ac5c4777efbf53a232ec91afa8b4c6b9d27979 ?
