### ISSUE TITLE
VSAN Top vmdk

### ISSUE THREAD

**Issue by hekyl** [sexibytes/sexigraf#251]
Hi, we can't see any VSAN VMs graphs in subj when they are part of any resource pool. We can only see those right under cluster  (vcenter host&cluster view) which aren't in RP , they are in "root". We can see in RVC console they are in different location, 
we are seeing those /localhost/Frontend Cloud/computers/<Cluster>/resourcePool/vms and thereis only few
but all ours vms are located /localhost/<DC>/vms and there are also a lot of sub resource pools so 99% of actual vms objects are   /localhost/<DC>/vms/<some vcloud director RP> (we have cloud director test environment>

We can't choose any other VM in Vsan Top vmdk, they are not existent for sexigraf.

so perhaps if there is a way to instruct sexigraf to look for VSAN VM in more locations would fix this.
We can see this behaviour in ravenholm, traptown and version 0.98

thanks
rg
peter

**Comment by rschitz** [comment]
Hi Hekyl, it doesnt matter where the vm is since we only look for the vmdk objects.
Can you send me the VsanDisksPullStatistics logs?

**Comment by hekyl** [comment]
Hi Raphael,
yes, certainly, sending requested. We’d like to have sexigraf working and so we have to cooperate obviously:)

 And sending the  screen where you will see…..almost no vmdks:-)
As I have to somwhat anononymize this log, please be aware that I replaced some IPs and crippled some fqdn, but lightly. 


rg
hekyl

**Comment by rschitz** [comment]
send me an email to plot[at]sexigraf.fr i'll send you a link to the latest beta if you want to check it out before sending me the logs, maybe it was something we fixed already

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/4414f763f7789ce3940fb19be6ae31668fd2c6db
