### ISSUE TITLE
Similar to #204 - Limiting web admin access to view only users

### ISSUE THREAD

**Issue by danilansible** [sexibytes/sexigraf#256]
Hi guys,

Version : 0.99f "Traptown"

I moved web admin json file from dashboards folder, but still it shows up in the web ui, any thoughts on how this can be achieved?

The whole point is to avoid unintentional config changes by view only users, and to make web admin page available(by moving back to dashboards folder?) on demand as needed.

sorry for reporting on an older version.

**Comment by rschitz** [comment]
Hi,

Did you restarted the grafana-server service after moving the file ?

**Comment by danilansible** [comment]
yes, Rebooted the system itself.

**Comment by rschitz** [comment]
ok let me try to find something but i cant promise anything since this version of grafana did not support folder auto provisioning, i'll get back to you soon but you should upgrade! lot of new features!

**Comment by danilansible** [comment]
Thank you so much.
I have a new version (which is excellent)running too and its easy with provisioning and permissions.
Also Couldn't see the manage permissions in the older version.

**Comment by rschitz** [comment]
Yeah in the newer version you can change the sexigraf folder permissions and that’s it. it's your best option IMHO

**Comment by rschitz** [comment]
i just check the 0.99f version and i'm almost sure you can't hide dashboards like you can in the latest version so sorry but you'll have to stick with the latest version to achieve that goal :)

**Comment by danilansible** [comment]
Got it. thank you @rschitz !

**Comment by rschitz** [comment]
sure, let me know if need something else and thanks for your amazing support!
