### ISSUE TITLE
dashboard metrics definition 

### ISSUE THREAD

**Issue by UnclePhil** [sexibytes/sexigraf#26]
hi, 

After implementation and 3 day of run i still does not have data in some graphics.
This is not a graphite problem but a Grafana dashboard definition problems
in may settings, you start your query with esx._.xxxx in place of vmw.$vcenter.$datacentre.$cluster.esx._.xxxx
and this is resulting in bad graph.
and due to the fact that you are using local dashboard, we need to patch this directly in the json files

Long work in perspective

Best regards
Ph Koenig
Belgium

**Comment by rschitz** [comment]
hi,

esx.$vcenter is for standalone where vmw.$vcenter is for host in cluster

What data is missing ?

On 9 oct. 2015, at 16:21, Philippe Koenig <notifications@github.com<mailto:notifications@github.com>> wrote:


hi,

After implementation and 3 day of run i still does not have data in some graphics.
This is not a graphite problem but a Grafana dashboard definition problems
in may settings, you start your query with esx..xxxx in place of vmw.$vcenter.$datacentre.$cluster.esx..xxxx
and this is resulting in bad graph.
and due to the fact that you are using local dashboard, we need to patch this directly in the json files

Long work in perspective

Best regards
Ph Koenig
Belgium

**Comment by UnclePhil** [comment]
![sexigraf-2015-10-09_20-43-23](https://cloud.githubusercontent.com/assets/471443/10402606/a97c057c-6ec6-11e5-92b2-77da0e0e5a27.png)

strange, 
As you can see in the picture, i do not have any esx. root data in the graphite repository.
but after the analysis of the ViPull script, i see that you are creating this one.

So i suppose that i have a problem with the script, and i suppose that the same problem is happening with the inventory who's  stopped with the "cant call method committed on a undefined value at line 111"

On which version of vsphere did you test this?? mine is a 5.5 
and how can i debug the perl pulling script

Ph Koenig

**Comment by UnclePhil** [comment]
the close was a bad manipulation...

![image](https://cloud.githubusercontent.com/assets/471443/10402635/d7fb128a-6ec6-11e5-948a-1f70832ad60c.png)

Strange, 
as you can see in the picture, the esx root data is not in the graphite.
i this i have a problem with a part of the pull script and i'm sure it's linked to the same problem that i have with the inventory
"cannot apply the method committed on undefined object on line 111"

on which version of vsphere are you developping ?? mine is a 5.5
an how can i debug this correctly ??

Best regard 
Philippe

**Comment by rschitz** [comment]
the script has been tested on 5.0, 5.5 and 6.0 so it's not related to API version IMHO but we faced multiple object name related issues during the QA so could you send us an export from RVTools so we can have a look on your naming convention?

**Comment by UnclePhil** [comment]
No more in Belgium for the moment but in Spain for the big vmw show...

But the global patter for physical and virtual machine is like "SVAPPCAVL007" one word , non point or comma, no special characters. And i'm sure there are no duplicate because that's something i check every week. 
If you are present at Barcelona we can maybe meet there.

Best regards

**Comment by rschitz** [comment]
Strange indeed...
we'll meet there for sure then ;)

**Comment by UnclePhil** [comment]
I just understand where is the not "so important problem". You a re using the esx. for server not in a cluster. and in the infrastructure i use to test the appliance, i don't have stand alone server ... so simple

Btw IMHO i found that this seggregation of server is breaking the integrity/coherence of the statistical data. And on same graph you are using both sources, whoe's, i think,  a bad mixing.
  
But i still have a problem with the inventory, and i try to find you at Barcelona to discuss this.
Did you have a booth there or are you walking like many other people ??
