### ISSUE TITLE
Removing cluster in vcentre, loses historical data in sexigrafs

### ISSUE THREAD

**Issue by syngress** [sexibytes/sexigraf#260]
Hi,

We've removed a couple of clusters in vcentre and it seems that the historical data relating to these clusters no longer shows in Sexigrafs. There is no way of selecting the old clusters. If I select a time period where the old clusters existed I have no way of selecting the name of the old cluster to show the data.

Is this expected behaviour? 

Thanks,

Mike

**Comment by rschitz** [comment]
Hi Mike, did you enabled the auto purge feature ?

**Comment by syngress** [comment]
Hi,

Auto purge is enabled – Don’t even remember doing this though 😊

Mike

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rschitz** [comment]
it is NOT enabled by default for this exact scenario ;)
