### ISSUE TITLE
Error downloading older SUP-files

### ISSUE THREAD

**Issue by acederlund** [sexibytes/sexigraf#262]
It seems like the older SUP-packages are no longer available, for example this does not work:
http://files.sexigraf.fr/sexigraf-0.99f.sup

I'm looking for the SUP files in order to step-by-step upgrading from 0.99e1 to 0.99g, and I suspect there may be issues importing/exporting between that old version and the new version.

Also, maybe not related to this issue, but how will upgrades be performed for newer releases? Via apt, or will we need to deploy new appliance again?

**Comment by rschitz** [comment]
it just uploaded all the sup files to https//dl.sexigraf.fr but you should be fine with export/import just give it a try with your old appliance running it's fine

**Comment by acederlund** [comment]
Thanks for the quick reply! I'll try this monday!

**Comment by rschitz** [comment]
you're very welcome, please let us know if it went well
