### ISSUE TITLE
Is there an easy way to change credentials for vcenters in credential store

### ISSUE THREAD

**Issue by danilansible** [sexibytes/sexigraf#266]
Hi ,

Is there an easy way to change credentials for vcenters in credential store other than "deleting and readding vcenter"
As part of security policy, password changes every 2 months so it would be great to know if there is a way to update new password in credential store

**Comment by rschitz** [comment]
Hi, i can give you the commands to automate the remove/add item in the credential store, would that suits you? We dont have api (yet) for this i'm sorry.

**Comment by danilansible** [comment]
That would be very helpful raphael @rschitz 
can you please share that

**Comment by danilansible** [comment]
Hi @rschitz 

Can you share the commands if you get a chance.

**Comment by rschitz** [comment]
/usr/lib/vmware-vcli/apps/general/credstore_admin.pl --credstore /var/www/.vmware/credstore/vicredentials.xml remove --server vcenter.vmware.local --username login

/usr/lib/vmware-vcli/apps/general/credstore_admin.pl --credstore /var/www/.vmware/credstore/vicredentials.xml add --server vcenter.vmware.local --username login --password Pa$$w0rd

**Comment by danilansible** [comment]
Much appreciated @rschitz 
Again, such a great project this is !

**Comment by rschitz** [comment]
You're welcome, it's going to be powershell in the future but i'll update this issue when it's done.
