### ISSUE TITLE
Sexigraf Ports

### ISSUE THREAD

**Issue by cacapis** [sexibytes/sexigraf#267]
Hi, is there a list of ports used by the Sexigraf appliance?

I'm assuming it uses 8080/8443 to connect to vCenter Web Services, and 2003 for Carbon, but are other ports used?

Thank you.-

**Comment by rschitz** [comment]
Hi, Only TCP 443 is used for vCenter/ESX, TCP 2003 is only used localy but it's also listening outside for other sources like FreeNas, Windows SSC or Proxmox
