### ISSUE TITLE
inventory export in csv from commandline

### ISSUE THREAD

**Issue by danilansible** [sexibytes/sexigraf#269]
Hi Raphael/team,

Offline inventory export is a cool feature, can you please guide me to call it from the server itself and write locally to a csv.
Got some hints from inventory.tmpl calling js datatables., couldn't move further though for a cmd level export

**Comment by rschitz** [comment]
Hi danilansible, to be honest we'll probably moving away from this offline inventory soon to build something more integrated into Grafana and beter at handling big inventories so you'll be able to export csv from grafana api i guess but i'll look into something to have a csv ready to download if that would be interesting to you?

**Comment by danilansible** [comment]
Thank you for the quick update.
yes, that definitely would be of great help. to be able to download in a cmd line freindly way or generate it in some local path on the server itself.

**Comment by danilansible** [comment]
@rschitz 
Excuse me checking if you got a chance to look at this.
No worries if its taking as you would be busy with making more interesting stuff available :)

**Comment by rschitz** [comment]
not yet sorry, i'll let you know ;)

**Comment by rschitz** [comment]
![image](https://user-images.githubusercontent.com/8385646/145694854-4c836276-6ddb-4cad-8b56-7277c7c64671.png)

![image](https://user-images.githubusercontent.com/8385646/145694870-3a65ca98-c5cb-474d-9549-782f73f87e96.png)
