### ISSUE TITLE
Implementation of a certificate

### ISSUE THREAD

**Issue by Ldenuziere** [sexibytes/sexigraf#270]
Hello,

I would like to implement a certificat that is a signed certificat (CA signed) for the web interface but I can't find any documentation.

Could you please explain me how to do it ?

Regards,

Loïc DENUZIERE

**Comment by rschitz** [comment]
Hi Loïc, thanks for support. We definitely need to document this you're right.
basically, you need to replace the existing one in the /etc/apache2/ssl/ folder and restart apache

**Comment by Ldenuziere** [comment]
Hello,

Thank you a lot for this reactivity !
Thank you for your answer I will do it.

Regards,

Loïc DENUZIERE



Loïc Denuziere
MS Engineer (L2)
France

M: 
+33 6 58761434
E: 
***@***.***
NTT France SAS is a subsidiary of NTT Ltd.
NTT France SAS with registration number 401 898 457 having its registered office at Creteil and its place of business at
Immeuble Venise, Parc Orly-Rungis, – 3 rue Saarinen Rungis Cedex CP 50337 94618.

**Comment by rschitz** [comment]
the easiest way is to keep the same file names to avoid changing anything in the site conf file

**Comment by Ldenuziere** [comment]
Hello,

When I try to restart the apache service, I hava an error :

![image](https://user-images.githubusercontent.com/90033484/132241491-e8a2482c-7d2b-411f-91da-bbbc4c8ee1c9.png)

Have you got an idea to help me ?

Regards,

**Comment by Ldenuziere** [comment]
By the way the file have the same name but it don't work

**Comment by Ldenuziere** [comment]
Hello, 
sorry I find why it didn't work and now it is ok
Regards,

**Comment by rschitz** [comment]
Check /var/log/apache2/error.log
