### ISSUE TITLE
Upgrade query

### ISSUE THREAD

**Issue by Spaggyboy** [sexibytes/sexigraf#273]
Hi,

We are still running 0.99f "Traptown" and would like to upgrade to the latest version. Apologies if this seems a little daft, but I am a little confused. The latest version 0.99g "Ravenholm" is only available as an OVA appliance and the import/export feature mentions that "importing a dump from a different version is not supported". Would this mean I'd have to setup a new OVA appliance from scratch? Or is there another way?

Many thanks

**Comment by rschitz** [comment]
Hi, actually this is our new and only way to upgrade from one version to another because of too many system changes so you can safely ignore this warning.
The only thing you might want to export manually is your custom dashboards that you need to export in json and import them in the new appliance.

**Comment by rschitz** [comment]
BTW, the exact message is "Beware that importing data from/to different version could cause some issues" ;)
