### ISSUE TITLE
Description for "VMware All Cluster Capacity Planning"

### ISSUE THREAD

**Issue by tsohst** [sexibytes/sexigraf#280]
Hello,
we're currently unsure what exactly the  "VMware All Cluster Capacity Planning" graphs are showing.
What unit does the y-axis have? And what does vm.on and vm.left mean?

**Comment by rschitz** [comment]
Hi, you got the details in the doc here https://www.sexigraf.fr/vsphere-sexipanels/#multi-cluster-capacity-planning

**Comment by tsohst** [comment]
Okay, understood.
But looking at the doc, there is a label on the y-axis, which is missing, thats why I was confued.
Can fix that myself ;)
![image](https://user-images.githubusercontent.com/32710648/150112116-45915a79-57d6-477e-8a31-9d6d6c6f570e.png)

**Comment by rschitz** [comment]
the y unit is a vm number, vm.on is the number of poweredon vm and vm.left is the number of average vm you could power on on that cluster

**Comment by tsohst** [comment]
Thank you for reply 👍
