### ISSUE TITLE
configure e-mail server for grafana alerts via SexiGraf Web Admin

### ISSUE THREAD

**Issue by tsohst** [sexibytes/sexigraf#281]
Hey,

we would like to configure alerts on certain graphs in grafana.
Is it possible to implement the configuration of the e-mail server in SexiGraf Web Admin?

**Comment by rschitz** [comment]
Hi,
Yes, you'd have to configure an email notification channel and an smtp server in the grafana config file https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/

**Comment by tsohst** [comment]
So, it is ok to manually edit things? Or can this break something when updating sexigraf in the future?

**Comment by rschitz** [comment]
in case of a minor update it's fine but in case of a major one you'd have to re-modify the file and recreate the alarm settings and export/import your custom dashboards

**Comment by rschitz** [comment]
Grafana 8 introduced a new alarms module so we have to make some change anyway
