### ISSUE TITLE
Add "datastore - vm" association to "VMware Multi Cluster Top N VM Latency"

### ISSUE THREAD

**Issue by tsohst** [sexibytes/sexigraf#282]
Hey,

is it possible to show the datastore where the vm resides on the moment it is having latency?
Like "$cluster.$vm.$datastore" when hovering?

![image](https://user-images.githubusercontent.com/32710648/150367090-1c3ce0f2-727e-45ae-86b8-1b6ff5d7b28a.png)

**Comment by rschitz** [comment]
Hi, no it's not possible due to the current way the data are organized in graphite i'm sorry
