### ISSUE TITLE
 VMware Multi Datastore Usage: monitor unused vmdks

### ISSUE THREAD

**Issue by tsohst** [sexibytes/sexigraf#283]
Hey,

is it possible to monitor vmdks which are not attached to any virtual machine?
We would like to find out if we're having dead vmdks which still consume space on the datastore.

**Comment by rschitz** [comment]
no because it's really time-consuming to search on datastore but i can send you a script link if you need

**Comment by tsohst** [comment]
Hey @rschitz, yes that script would be really helpfull :)

**Comment by rschitz** [comment]
http://www.hypervisor.fr/?p=3612
i dont have time to finish a proper script for now so here is the oneliner version
