### ISSUE TITLE
VMware All Cluster VM Stats: Add Graph of IOPS and Blocksize

### ISSUE THREAD

**Issue by tsohst** [sexibytes/sexigraf#284]
Hello,
It would be great if the VMware All Cluster VM Stats board would also contain a graph of IOPS and Blocksize of a virtaul machine.

**Comment by rschitz** [comment]
i'll add iops since you're not the first one to ask but blocksize is something almost only used for troubleshooting and i'm trying to limit the number of collected metrics to keep the appliance as light as possible. hope you'll understand.

**Comment by rschitz** [comment]
![image](https://github.com/sexibytes/sexigraf/assets/8385646/fe71272b-f8eb-4fab-931b-e5aba332ef58)
