### ISSUE TITLE
SexiGraf VI Offline Inventory panel does not refresh

### ISSUE THREAD

**Issue by ttmader** [sexibytes/sexigraf#286]
Hello!

I am seeing that the SexiGraf VI Offline Inventory panel does not refresh. In the rest of the panels it is updated. 

![image](https://user-images.githubusercontent.com/60410678/154058643-cc188553-7566-458f-b535-d29f963065d9.png)

Coincidentally, it was the last time the Sexigraf had been reset. After reboot it still won't update. I have also forced the update without success.

what is the reason?

Thanks a lot.

**Comment by rschitz** [comment]
Hi, thanks for your support.
The very soon coming next release will take care of this issue and will handle non responding vcenter ;)

**Comment by rschitz** [comment]
BTW, would you like to test the latest version soon to be GA?
