### ISSUE TITLE
Maximum vCenter amount

### ISSUE THREAD

**Issue by rapha57** [sexibytes/sexigraf#288]
Hi everyone,

I would like to know how much vCenter can be added to the product?

Right now, I got 3 vCenter connected but when I want to add a new one, nothing happens.

This is a limitation or a just bug?

Ty.

**Comment by rschitz** [comment]
Hi, with the right amount of ram and cpu you go up to 50 easily, there is no limitation.
if anything goes wrong during the addition, you should get an error message

**Comment by rapha57** [comment]
Tried to add more ram (from 8 to 16 Gb), but the issue still occurs.

After press the Add button, nothing happens and no error message occurs. Another strange thing, if I turn back to the Administration panel, I get black screen and categories appears few seconds later (around 45-60).

Maybe I have to redeploy the OVA ?

PS: For each vCenter, I use the same account (configured to only have the read access on the entire infrastructure).

**Comment by rschitz** [comment]
something maybe wrong in the server/account validation, would you agree to try on the next version we're about to release? the appliance is ready to ship, we're just finishing the documentation so you'd be able to keep it in production and also validate the migration process as well

**Comment by rapha57** [comment]
I can try, no problem. Let's see if the new release can avoid this behavioir :)

**Comment by rapha57** [comment]
Sent ;)

**Comment by rapha57** [comment]
Solved with the latest build.
