### ISSUE TITLE
SHA1 checksum incorrect?

### ISSUE THREAD

**Issue by Myer** [sexibytes/sexigraf#292]
Is the SHA1 checksum posted here [https://www.sexigraf.fr/quickstart/](https://www.sexigraf.fr/quickstart/) correct for the latest v0.99h “Highway 17” release?
I'm getting another SHA1 sum...

**Comment by rschitz** [comment]
Sorry i had to make a small change, I'll update the SHA1 sum.

Thanks a lot for reporting it

**Comment by rschitz** [comment]
sha1 fixed, thanks again
