### ISSUE TITLE
No data but show machines inventory

### ISSUE THREAD

**Issue by ttmader** [sexibytes/sexigraf#296]
Hello,

I have deployed the latest version of the OVA to test it and I have added a vcenter, both by ip and by dns. I have also added ESXi, by ip and by dns. None show graphs but in the inventory the virtual machines do appear.

I have also installed the agent for Windows and the machine appears but without metrics.

What's going on?

Thanks.

**Comment by rschitz** [comment]
Hi, in the action menu, did you clicked on "enable VI" ?
![image](https://user-images.githubusercontent.com/8385646/165903731-07404b3e-047f-4b02-bed6-6aae14a21213.png)
for the windows agent we might need you to check the content of the /mnt/wfs/whisper/SSC/ folder on your SexiGraf appliance to see if you got any folders and files

**Comment by ttmader** [comment]
Hi,

I have verified that metrics do appear but only when I put "Last 3 hours". It happens with all graphs.

![image](https://user-images.githubusercontent.com/60410678/166293724-8e1018eb-d19b-4cdf-8a29-0ec672985ce4.png)

![image](https://user-images.githubusercontent.com/60410678/166293744-3c990b80-a120-4c7d-8085-89d207c488f3.png)

What can be the motive?

Thanks.

**Comment by rschitz** [comment]
That means there is an issue in the collect, can you check the logs in the admin dashboard please?

**Comment by jagitojago** [comment]
Hi Raphael

I have similar issues
A) Only objects are seen on inventory tab but not on other tabs
B) I only see two from three vcenters (only two vcenters are visible to be
selected)  althoughI have the same config on another sexigraf vm and there
I can see all three vcenters active

Attached the logs

Sincerely and thanks for your wonderful Job!

TIA

Jago :)

**Comment by rschitz** [comment]
Hi Jago, thanks a lot for your support.
No logs in your msg, send them to plot[at]sexigraf.fr please

**Comment by rschitz** [comment]
it looks like you got the same issue as another user, no vmotion/svmotion metrics on a cluster, can you try this new version of the script please https://github.com/sexibytes/sexigraf/blob/develop/opt/sexigraf/ViPullStatistics.ps1 ?

**Comment by ttmader** [comment]
> That means there is an issue in the collect, can you check the logs in the admin dashboard please?

It also happens with the "home" panel:

![image](https://user-images.githubusercontent.com/60410678/166515302-becb9583-e4b6-4763-8a75-89648748c85c.png)

![image](https://user-images.githubusercontent.com/60410678/166515347-d0390c95-918f-49ee-b985-49a369f29261.png)

**Comment by rschitz** [comment]
@ttmader can you sen me the logs to plot[at]sexigraf.fr please?

**Comment by jagitojago** [comment]
Hi Raphael

New PS script implemented





Findings: (some examples)



*VMware vSAN/VMware vSAN Monitor tab*

*Does not show vSAN data output*



*VMware vSAN/VMware vSAN Monitor* NetWork  tab

Also no output for vSAN





VMware Cluster/VMware Cluster FullStats



*Still no data from one of the three vCenters (only two visible) (anyway
Cluster List shows Clusters from that vCenter but no data is outputted.*




*Attached Log File*

*KR*


*Jago*

**Comment by rschitz** [comment]
@jagitojago can you sen me the logs to plot[at]sexigraf.fr please?
