### ISSUE TITLE
Direct link rendered image not working

### ISSUE THREAD

**Issue by raphoun** [sexibytes/sexigraf#301]
Hello

Getting this error in grafana.log
`t=2022-06-01T07:50:26+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="rendering failed: Error: Failed to launch the browser process!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"
`

Regarding this page https://grafana.com/docs/grafana/latest/image-rendering/troubleshooting/ some additionnal packets are needed on Ubuntu
libx11-6 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrender1 libxtst6 libglib2.0-0 libnss3 libcups2  libdbus-1-3 libxss1 libxrandr2 libgtk-3-0 libasound2 libxcb-dri3-0 libgbm1 libxshmfence1

Is it possible to add them in the next Sexigraf version?

**Comment by rschitz** [comment]
Hi, it's supposed to be installed https://github.com/sexibytes/packer-sexigraf/blob/ba0c09758974ce9c631cc69935e02fe0ae5ff514/scripts/grafana.sh#L3
Can you check you got the latest ova installed?
