### ISSUE TITLE
How to change timezone JST?

### ISSUE THREAD

**Issue by maopan415** [sexibytes/sexigraf#310]
Hi, SexyGraf is very nice monitorg tool. 

I have a question, I want to change sexigraf timezone JST.
I changed config file `/etc/localtime`, `/etc/grafana/grafana.ini`
so sexigraf dashboard and status captured in vmw are changed timezone JST. 
but event infomation captured in vi are not change timezone. 
Only vi event information is displayed in UTC.
How to change vi event information displayed in JST?

Do you have any ideas? 
thanks.

**Comment by rschitz** [comment]
Hi, thanks for your support!

You should leave the configuration in UTC and only change the timezone in the org configuration so the dashboards would inherit it:

![image](https://user-images.githubusercontent.com/8385646/201865833-01d50584-b8df-4ae8-8c1c-a4b10034a04f.png)

**Comment by rschitz** [comment]
default is browser time BTW

**Comment by maopan415** [comment]
Hi, thanks for help!
I changed the server configuration in UTC and change the timezone in the org configuration.
so The time display on the dashboard is changed, but the event occurrence time is displayed as UTC+9:00(timezone config) instead of the actual occurrence time.

The event actually occurred at 14:00, but displayed at 22:00 on the dashboard.
How to fix it? 
Thanks.

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/115207339/202055383-f6a35167-08ca-48db-956d-6eca4baa1aed.png">

**Comment by rschitz** [comment]
If you check any dashboard, does the timeline match your current timezone?

**Comment by rschitz** [comment]
No problem, glad you found the issue ;)
