### ISSUE TITLE
Is Alerting possible for other dashboards too like vcenter bad events

### ISSUE THREAD

**Issue by danilansible** [sexibytes/sexigraf#315]
Hi ,
Can you guide on if alerting can be configured on templated dashboards. It's doesn't show edit option for these it looks like
Thank you.

**Comment by rschitz** [comment]
https://github.com/grafana/grafana/issues/10412#issuecomment-355002076

**Comment by rschitz** [comment]
You'll have to clone existing dashboard and set the assets you want to monitor (or use *) i'm afraid

**Comment by rschitz** [comment]
Unified Alerting looks like a white elephant, we'll look into it for the next version since it seems complicated to automate.
#320
