### ISSUE TITLE
Add ability to load interface in HomeAssistant as iFrame

### ISSUE THREAD

**Issue by meharrington90** [sexibytes/sexigraf#316]
Hey there,

I wanted to integrate this page into HomeAssistant as an iFrame, but was unable to do so because of the current config. I was able to modify the files in the OVA instance, and got it functional making these changes in the `grafana.ini` config:

- allow_embedding = true
- auth.anonymous
- enabled = true
- org_name = <<org name>>
- org_role = Viewer

Easy fixes, but it could help a lot of people.

By the way I was trying to do all the work you've done on this project MANUALLY, and I am so ecstatic I found your project. Thank you so much, you saved me days of configuration headaches.

**Comment by rschitz** [comment]
Thanks a lot for your support and sharing the tips.
If you;re intereseted, i once figure out how to regulary export a screenshot of a dashboard for external use for a project : http://ron106.fr/FR/
