### ISSUE TITLE
Datastores used space metric

### ISSUE THREAD

**Issue by danilansible** [sexibytes/sexigraf#334]
Hi ,

Using latest version, Regarding alerting, this query  vsan.*.*.*.esx.*.vsan.disk.capacity.*.percentUsed gives the Local esx disks used capacity.
Looked around but Couldnt figure out what/where the corresponding metric for datastores(vsan/shared datastores) is, so that if space usage crosses a threshold I can trigger an alert

Any thoughts please?
Thanks

**Comment by rschitz** [comment]
Hi, it's not included indeed because SexiGraf was not intended for alerting in the first place.
I could include the metric for the next version if you want it? I could also create a dedicated dashboard with space usage gauges, that would be a nice touch

**Comment by danilansible** [comment]
That would be a great addition if possible.  Thank you @rschitz 
Much appreciated!

Btw, after a lot of trial and errors with messaging templates(complex) of grafana, was able to setup some decent alerting.I can share that if someone needs in the other thread where dumped some queries for alerting.

**Comment by rschitz** [comment]
if you are brave enough and have nice screenshots we could offer you to write a blog post on the sexigraf.fr website?
