### ISSUE TITLE
Appliance network settings

### ISSUE THREAD

**Issue by UAnton** [sexibytes/sexigraf#338]
hi,
Netplan removed - why?
I can't add DNS servers... after the reboot config is restored. Why you broke standard Networking in Ubuntu?
No network after deploying OVA.

**Comment by rschitz** [comment]
Hi, we did this to make it easier to configure the vm during deployment and reconfigure the vm in the vCenter later if needed.
If you need to make changes, shutdown the vm and edit the vApp Options:
![image](https://user-images.githubusercontent.com/8385646/224976114-ca8ba1f6-017b-4071-a64f-9cbcf2283c48.png)

We've edited the quickstart page, thanks for your support
https://www.sexigraf.fr/quickstart/
