### ISSUE TITLE
Adding VMNIC CRC error check

### ISSUE THREAD

**Issue by mithun2186** [sexibytes/sexigraf#344]
Hello team 

is there a way we can add CRC error for VMNIC as part of data collection ?

**Comment by mithun2186** [comment]
Get-Cluster -PipelineVariable cluster | 
Get-VMHost -PipelineVariable esx |
ForEach-Object -Process {
  $esxcli = Get-EsxCli -VMHost $esx -V2
  $esxcli.network.nic.list.Invoke() |
  ForEach-Object -Process {
    $esxcli.network.nic.stats.get.Invoke(@{nicname=$_.Name}) |
    Select @{N='Cluster';E={$cluster.Name}},
      @{N='VMHost';E={$esxcli.VMHost.Name}},
      NICName,PacketsReceived,PacketsSent,ReceiveCRCerrors
  }  
}

**Comment by rschitz** [comment]
Hi, in case you didn't noticed we got this already https://www.sexigraf.fr/vsphere-sexipanels/#cluster-network-usage
Also, we can't get anything else from the metrics: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/network_counters.html
