### ISSUE TITLE
¿Remove old cluster?

### ISSUE THREAD

**Issue by ttmader** [sexibytes/sexigraf#346]
Hello,

We have some cluster that were created from tests and we want to delete them but I don't see the option inside SexiGraf House Cleaner.

How can you delete these clusters?

Thank.

**Comment by rschitz** [comment]
Hi, we will improve the house cleaner tool but you can use the purge older than X days to purge deleted items:
![image](https://github.com/sexibytes/sexigraf/assets/8385646/34550ca4-b248-46f8-b746-b4324a96dc10)

**Comment by ttmader** [comment]
It would be interesting to put this improvement to delete only cluster and not delete machines from other environments.

I'll keep it in mind.

Thank you very much for your help!

**Comment by rschitz** [comment]
replace "2" by "3" in /var/www/admin/purge.php line 79
refresh the house cleaner page and unfold the folders, you should now see clusters after datacenters
this change will be added in the next release

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/2bebae8784c55fdc570eec9fbc9e48d6798e4d07

![image](https://github.com/sexibytes/sexigraf/assets/8385646/d40c03d7-e2e1-4ac7-b42c-865b2b72249c)
