### ISSUE TITLE
CPU ready in Sexigraf for vmware vm does not match the data in Vcenter

### ISSUE THREAD

**Issue by torck82** [sexibytes/sexigraf#348]
I'm comparing the data for CPU ready for VMs, and the data does not match what I see in Vcenter for the Vms.

In SexiGraf CPU ready at 16:50 was at 3.56 percent CPU ready, but in VCenter the VM CPU ready is 13.44 at the same time.

**Comment by rschitz** [comment]
in vCenter, ready is in ms whereas in SexiGraf it's in %, if you want to compare, use readiness metric which follow the formula:
<img width="577" alt="image" src="https://github.com/sexibytes/sexigraf/assets/8385646/ab779020-708a-4006-a712-a0073c04b4ba">
https://kb.vmware.com/kb/2002181

**Comment by torck82** [comment]
Thanks, I compared that also and the data is still off by a lot.
