### ISSUE TITLE
Where do you get the data to display com_vmware_vc_authorization_nopermission?

### ISSUE THREAD

**Issue by ttmader** [sexibytes/sexigraf#363]
Hello

These events have been appearing to me since the 13th.

![image](https://github.com/sexibytes/sexigraf/assets/60410678/baef2a25-0d97-4d71-bb12-22bcb101f576)

I've searched some logs, and I don't see anything with that description.

I need to detect the problem.

I hope your help.

Thanks

**Comment by rschitz** [comment]
check the events on the vcenter object and look for permissions issues like this:

![image](https://github.com/sexibytes/sexigraf/assets/8385646/b429b8aa-fa7a-42c5-9593-480beb05090b)

**Comment by ttmader** [comment]
Hello.

I don't know how I was searching, honestly. She was much easier than she thought. I have already seen that in the events, the Event Type ID appears.

I will keep it in mind for the future. As always, THANK YOU!

**Comment by rschitz** [comment]
welcome mate ;)
