### ISSUE TITLE
Time data request Error on graph

### ISSUE THREAD

**Issue by jeebee2013** [sexibytes/sexigraf#37]
Hi team
Congratulation for this amazing tool
i've got one issue on my test lab (Vsphere 6) 
on the Vmware FlambX \ HDD graph, i've a red ! with "Time data request Error "
i have the same on VMWARE esx Full stat... and on some other graph expecially on datastore or Hdd graph.
i've seen that there is some similar issue related to Grafana.. but without any detail.
any idea ?

thanks

julien

**Comment by rschitz** [comment]
Thanks Julien. It's most likely related to naming issues like 2 items with the same name. Something like that in your setup?

**Comment by jeebee2013** [comment]
hello
i don"t have (as far as i know :-) 2 item with same same
my home lab is on 2 ESX with different name 
Datastore have different name also

thanks for your help

**Comment by jeebee2013** [comment]
hello
i 've setup a new fresh sexigraf VM.
i've the same issue all that concern storage have the "! TIME Data request error."

jb

**Comment by rschitz** [comment]
Can you send us the whisper.log generated by this command:
find /var/lib/graphite/whisper -type d -print > /tmp/whisper.log

**Comment by miquelMariano** [comment]
Hi, i have the same issue

This is my whisper.log

root@sexigraf:~# cat /tmp/whisper.log
/var/lib/graphite/whisper
/var/lib/graphite/whisper/carbon
/var/lib/graphite/whisper/carbon/agents
/var/lib/graphite/whisper/carbon/agents/sexigraf-a
/var/lib/graphite/whisper/carbon/agents/sexigraf-a/cache
/var/lib/graphite/whisper/vmw
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/quickstats
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/quickstats/cpu
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/quickstats/mem
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/runtime
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/runtime/vm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net/vmnic3
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net/vmnic4
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net/vmnic1
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net/vmnic5
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net/vmnic0
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/net/vmnic2
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi02/quickstats
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net/vmnic3
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net/vmnic4
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net/vmnic1
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net/vmnic5
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net/vmnic0
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/net/vmnic2
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/esx/esxi01/quickstats
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun002
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun002/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun002/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun004
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun004/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun004/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun000
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun000/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun000/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun001
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun001/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun001/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun003
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun003/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun003/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/lun1-co
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/lun1-co/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/lun1-co/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02-lun001
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02-lun001/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02-lun001/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun005
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun005/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas01_lun005/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02-lun000
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02-lun000/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02-lun000/summary
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02_lun002
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02_lun002/iorm
/var/lib/graphite/whisper/vmw/ncora-vcenter_ncora_local/ncora/cluster/datastore/sas02_lun002/summary
/var/lib/graphite/whisper/collectd
/var/lib/graphite/whisper/collectd/sexigraf
/var/lib/graphite/whisper/collectd/sexigraf/df-root
/var/lib/graphite/whisper/collectd/sexigraf/cpu-1
/var/lib/graphite/whisper/collectd/sexigraf/load
/var/lib/graphite/whisper/collectd/sexigraf/load/load
/var/lib/graphite/whisper/collectd/sexigraf/cpu-0
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0/if_errors
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0/if_packets
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0/if_octets
/var/lib/graphite/whisper/collectd/sexigraf/aggregation-cpu-average
/var/lib/graphite/whisper/collectd/sexigraf/memory
/var/lib/graphite/whisper/vi
/var/lib/graphite/whisper/vi/ncora-vcenter_ncora_local
/var/lib/graphite/whisper/vi/ncora-vcenter_ncora_local/vm
/var/lib/graphite/whisper/vi/ncora-vcenter_ncora_local/vm/exec
/var/lib/graphite/whisper/vi/ncora-vcenter_ncora_local/vi
/var/lib/graphite/whisper/vi/ncora-vcenter_ncora_local/vi/exec


Thank you

**Comment by ethermcman** [comment]
Same here...
My whisper.log:
/var/lib/graphite/whisper
/var/lib/graphite/whisper/carbon
/var/lib/graphite/whisper/carbon/agents
/var/lib/graphite/whisper/carbon/agents/sexigraf-a
/var/lib/graphite/whisper/carbon/agents/sexigraf-a/cache
/var/lib/graphite/whisper/vmw
/var/lib/graphite/whisper/vmw/192_168_155_93
/var/lib/graphite/whisper/vmw/192_168_155_93/rm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/quickstats
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/quickstats/cpu
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/quickstats/mem
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/runtime
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/runtime/vm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic7
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic4
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic1
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic6
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic5
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic0
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/net/vmnic2
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx1/quickstats
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic7
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic3
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic4
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic6
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic5
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic0
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/net/vmnic2
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/esx/srv-esx2/quickstats
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-03
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-03/iorm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-03/summary
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-02
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-02/iorm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-02/summary
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-01
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-01/iorm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-01/summary
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/nfs-01
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/nfs-01/iorm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/nfs-01/summary
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-04
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-04/iorm
/var/lib/graphite/whisper/vmw/192_168_155_93/rm/ha-cluster/datastore/vmfs-04/summary
/var/lib/graphite/whisper/collectd
/var/lib/graphite/whisper/collectd/sexigraf
/var/lib/graphite/whisper/collectd/sexigraf/df-root
/var/lib/graphite/whisper/collectd/sexigraf/cpu-1
/var/lib/graphite/whisper/collectd/sexigraf/load
/var/lib/graphite/whisper/collectd/sexigraf/load/load
/var/lib/graphite/whisper/collectd/sexigraf/cpu-0
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0/if_errors
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0/if_packets
/var/lib/graphite/whisper/collectd/sexigraf/interface-eth0/if_octets
/var/lib/graphite/whisper/collectd/sexigraf/aggregation-cpu-average
/var/lib/graphite/whisper/collectd/sexigraf/memory
/var/lib/graphite/whisper/vi
/var/lib/graphite/whisper/vi/192_168_155_94
/var/lib/graphite/whisper/vi/192_168_155_94/vm
/var/lib/graphite/whisper/vi/192_168_155_94/vm/exec
/var/lib/graphite/whisper/vi/192_168_155_93
/var/lib/graphite/whisper/vi/192_168_155_93/vm
/var/lib/graphite/whisper/vi/192_168_155_93/vm/exec
/var/lib/graphite/whisper/vi/192_168_155_93/vi
/var/lib/graphite/whisper/vi/192_168_155_93/vi/exec
/var/lib/graphite/whisper/vi/192_168_155_95
/var/lib/graphite/whisper/vi/192_168_155_95/vm
/var/lib/graphite/whisper/vi/192_168_155_95/vm/exec

Thank you too.

**Comment by miquelMariano** [comment]
https://github.com/sexibytes/sexigraf/issues/39#issuecomment-165726793

**Comment by ethermcman** [comment]
Thanks for your reply : I've already seen this answer ;)
Does it state that it doesn't work in a mixed environment? I've a cluster with 2 hosts and one standalone ESXi.
