### ISSUE TITLE
Rounding in FlambX

### ISSUE THREAD

**Issue by zsoltesz** [sexibytes/sexigraf#38]
Hi,

Not a big issue, but the RAM capacity in the FlambX graf, when it is more than 1 TB, is rounded to whole number. For example in case of 1,37TB tha graf shows only 1TB.

Regards,
Zoli

**Comment by rschitz** [comment]
Thanks for reporting that, we already discussed about that internally and in case you have a small screen you may encounter this: 
<img width="422" alt="screen shot 2015-12-14 at 14 29 16" src="https://cloud.githubusercontent.com/assets/8385646/11782109/415ee3ec-a26f-11e5-9d23-073dcfb0e841.png">

We changed the dev dashboard, please try it: https://github.com/sexibytes/sexigraf/blob/dev/var/lib/grafana/dashboards/VMware_FlambX.json

**Comment by zsoltesz** [comment]
Hi,

It is my fault, but I cannot try the corrected version. Could you tell me how can I add this version to my installed Sexigraf?

Zoli

**Comment by rschitz** [comment]
Hi, you'll find the import/export doc here http://docs.grafana.org/reference/export_import/

**Comment by zsoltesz** [comment]
Thank you for your help. I have managed to import. It seems good.
Zoli
