### ISSUE TITLE
Export report capabilities 

### ISSUE THREAD

**Issue by MihirP1129** [sexibytes/sexigraf#380]
Could you please add a feature to provide reporting from dashboards so we can provide to the executives?

**Comment by rschitz** [comment]
unfortunately, the report feature is a licensed feature from grafana enterprise version (https://grafana.com/docs/grafana/latest/dashboards/create-reports/) what you could do is use the sharing features on the desired graf to get a clean png file

![image](https://github.com/sexibytes/sexigraf/assets/8385646/88fc3987-2f5b-488c-bd2e-c746e15c53ca)

![image](https://github.com/sexibytes/sexigraf/assets/8385646/f91d010a-4c91-4c4e-98d2-2b0ce1fdc909)

you can also use an api key to automate this 

![image](https://github.com/sexibytes/sexigraf/assets/8385646/bc9162f4-5884-488b-a02e-dc42c6d49982)

**Comment by MihirP1129** [comment]
Ok thanks!

**Comment by rschitz** [comment]
you're welcome ;)
what kind of report would you need?

**Comment by MihirP1129** [comment]
So we use Veeam to get reports for forecast/capacity planning,
overprovisioned/underprivisioned resources.

**Comment by rschitz** [comment]
capacity planning that's possible but forecast is not possible with grafana/graphite unfortunately.
underprovisioned is also easy to figure out but underprivisioned is also a bit tricky.
i'll make a blog post to document the graf download automation and let you know, in the mean time you'd have to find a way to put in a pdf file with text and all :)

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/issues/403
