### ISSUE TITLE
VMware Multi ESX QuickStats

### ISSUE THREAD

**Issue by zsoltesz** [sexibytes/sexigraf#39]
Hi,

There is an another issue. The VMware Multi ESX Quickstats does not present any data, and I cannot select anything in the header part. 
Is it a known issue or something wrong with my local installation?

Regards,
Zoli

![multi_esx-quickstats](https://cloud.githubusercontent.com/assets/16287260/11835057/eba2c298-a3d1-11e5-8886-809d9926e095.png)

**Comment by miquelMariano** [comment]
Hi

I have te same problem

Any ESXi dashboard is empty and view "Timeseries datarequest error"

Thank you
![captura](https://cloud.githubusercontent.com/assets/12425938/11868339/3b6f7894-a4b7-11e5-906f-34b759cfb50e.PNG)

**Comment by rschitz** [comment]
This dashboard is dedicated to standalone ESX not for cluster members. Do you have any ?

**Comment by zsoltesz** [comment]
I am sorry, I misunderstood it. Do you plan to make a graf to present the full stats of the ESXi hosts of a cluster?

Zoli

**Comment by miquelMariano** [comment]
OK rschitz, in my environment i don't have standalone ESXi, but i put a node temporarily and the graphics are displayed ok

Thanks

**Comment by sexibytes** [comment]
Please try VMware Cluster Multi ESX LiteStats
We'll correct that misslead in the future.
