### ISSUE TITLE
Option to use MAC Address instead of Client-ID when using DHCP

### ISSUE THREAD

**Issue by TheFou** [sexibytes/sexigraf#397]
Hi,
I wanted to set a reservation in Windows DHCP server, but kept getting a client-ID instead of the mac address (this way I just set the same MAC when upgrading).
Tried to change /etc/netplan/xxx.yaml, but found out you didn't use that.
I finally added `send dhcp-client-identifier = hardware;` in /etc/dhcp/dhclient.conf, and it worked.
Could you please provide the option directly when deploying the OVA ?
Or set this to MAC address by default.

Thanks for your work 😉

**Comment by rschitz** [comment]
Hi and thanks for your support.
i can add `send dhcp-client-identifier = hardware;` in /etc/dhcp/dhclient.conf for sure but why not setting a fixed ip during the ova deploy? (just asking)

**Comment by TheFou** [comment]
Hi,
Honestly, nothing more than habits... I usually set fixed IP only for really critical stuff, and set reservations for everything else that would need fixed IP.
It's only for a small homelab in that case, not a complex corporate setup.
Maybe I'm missing something, but I didn't find any advantage to the client-ID used by Ubuntu, and unfortunately Windows being Windows, it is only compatible with MAC Addresses for reservations.
So I think MAC Address being the default option should not impact anything, but I may be wrong.
If anyone has a use-case where client ID is required or is a better option, I'm interested to hear about it.
Thanks !

**Comment by TheFou** [comment]
Yeah of course

**Comment by rschitz** [comment]
![image](https://github.com/sexibytes/sexigraf/assets/8385646/b5096bce-dac5-4932-93d9-c9c36c695336)

**Comment by rschitz** [comment]
shoot me an email at plot[at]sexigraf[dot]fr and i'll share you a link
