### ISSUE TITLE
Offline Inventory : Resource Pool name & vm folder path

### ISSUE THREAD

**Issue by flamby** [sexibytes/sexigraf#42]
Hi,

Would be useful to get
- Resource pool name (think VCD use-case : org vDC)
- vm folder path (e.g. Cloud/tenant1/vdc_name/vapp_name ; again VCD use-case)

Thus, sexigraf becomes the offline cloud inventory "par excellence"

**Comment by vmdude** [comment]
VM Folder path has been added with 204b82915c620330062dcde205e3d7bbbffc347f
Resource Pool will be discussed for next version :)
