### ISSUE TITLE
Add NAA latencies dashboard for VSAN

### ISSUE THREAD

**Issue by rschitz** [sexibytes/sexigraf#44]

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/dbbc7281874a70cd7bf5c8aa02ce835257617f7a

**Comment by rschitz** [comment]
![chrome_2016-02-20_18-00-41](https://cloud.githubusercontent.com/assets/8385646/13197920/e170aa70-d7fb-11e5-978d-8c020ba2d374.png)

**Comment by millardjk** [comment]
Love the dashboard, but wish it could optionally/alternatively show the name of the device (which can be changed to something representative like "host3.disk05") instead of the underlying NAA ID.

**Comment by rschitz** [comment]
Actually i can't event add the host name in the graph title...

**Comment by rschitz** [comment]
![named_naa](https://cloud.githubusercontent.com/assets/8385646/20108022/f7ecc4de-a5da-11e6-9bda-3ed7d7757653.png)

Something like that?

**Comment by rschitz** [comment]
(ESX hostname next to the red dash)

**Comment by millardjk** [comment]
the red dash is the hostname or the device name? Hostname is helpful, but it's the device name that I'm actually looking for (I put the hostname into the device name anyway).

**Comment by rschitz** [comment]
oh i'm sorry no it's not possible as is but if you have the hostname AND the naa, why do you need the device name anymore for?

**Comment by millardjk** [comment]
By using the rename function on the device, you can get to the actual device much faster than using hostname & naa. But if it's a limitation, you live within those and go from there...
![screenshot - 11_8_2016 11_24_32 am](https://cloud.githubusercontent.com/assets/16329621/20109528/0f804b50-a5a6-11e6-99ae-9d93b7945156.png)

**Comment by rschitz** [comment]
The VSAN APIs only expose the naa as device name so you'll have to deal with it i'm afraid.
At least you have the hostname now :D

**Comment by millardjk** [comment]
I'll take it.
