### ISSUE TITLE
FlambX dashboard issue with number of ESXi hosts

### ISSUE THREAD

**Issue by tsugliani** [sexibytes/sexigraf#59]
It seems the calculation will fail if no standalone hosts are available. (X + N/A = N/A or Error)

In my case I didn't have any so just disabled the second metric & the final sumseries calculation.

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/e5fc6fa857e80dfde42238779eeefff7d4170a3a#diff-13a5bfb20fe9399458d1ca2ab3a40d94

**Comment by rschitz** [comment]
It was actually bad json syntax.
