### ISSUE TITLE
Aggregated Datastore IOPS No datapoints

### ISSUE THREAD

**Issue by miquelMariano** [sexibytes/sexigraf#60]
Hi guys!!!

In the dashboard VMWare IORM Cluster Stats, the panel Aggegated Datastore IOPS display No datapoints.

I think that the metric **datastoreIops** is missing in my DB

![image](https://cloud.githubusercontent.com/assets/12425938/14345097/7c93d2ce-fcab-11e5-9e0c-8a1b14765ada.png)

Any idea??

Thanks a lot!

**Comment by rschitz** [comment]
That's expected if you did not enable the SIOC stats collection as explain here http://www.sexigraf.fr/vsphere-sexipanels/ "In the IORM row, you’ll find the average latency and the IOPS sum..."

**Comment by rschitz** [comment]
could you enable it and let us know if that solves your issue?

**Comment by miquelMariano** [comment]
Yes, i enable the storage I/O statistics and the graph is displayed correctly

![image](https://cloud.githubusercontent.com/assets/12425938/14354262/e4acfc9c-fcdc-11e5-9a14-ed43eb085e5e.png)


Thanks for you answer and for this awesome monitoring tool

;-)

**Comment by MacroPower** [comment]
I have this same issue, but when I enabled collection I still have no datapoints. Am I missing something here?

**Comment by miquelMariano** [comment]
Ensure that SIOC has been enabled on your datastores

![image](https://cloud.githubusercontent.com/assets/12425938/24139210/8a9b12e2-0e1b-11e7-99db-143130bd0990.png)

**Comment by MacroPower** [comment]
Sorry for the late reply. Here is my config...

![image](https://cloud.githubusercontent.com/assets/5648814/24506676/47a19bc4-152c-11e7-886c-b9cbc16e20ee.png)
