### ISSUE TITLE
Dashboard init failed Template variables could not be initialized: undefined

### ISSUE THREAD

**Issue by chambess** [sexibytes/sexigraf#62]
Comme discuté sur Twitter sur la majorité des dashboards j'ai cette erreur.
Ci-joint les logs de /var/log
[Sexigraf_log.zip](https://github.com/sexibytes/sexigraf/files/209894/Sexigraf_log.zip)

**Comment by rschitz** [comment]
A mon avis c'est ton "région_alsace" le problème.
si tu veux en avoir le coeur net, tu arrêtes la collecte (disable VI dans le cred store) et tu renomme le répertoire dans /var/lib/graphite/whisper

**Comment by chambess** [comment]
Hello,

C'est bien ça, quand je renomme /var/lib/graphite/whisper/vmw/r?gion_alsace en region_alsace les dashboard s'initialisent correctement. Par contre après 2/3 min (après avoir redémarré la collecte), le répertoire /var/lib/graphite/whisper/vmw/r?gion_alsace réapparaît et l'initialisation est à nouveau en erreur.

Y a-t-il un moyen de résoudre le problème  sans que je renomme mon Datacenter?

Merci d'avance :)

Envoyé de mon iPhone

**Comment by rschitz** [comment]
Oui tu peux faire un lien symbolique et l'utiliser dans les dashboard au lieu l'original 


> Y a-t-il un moyen de r�soudre le probl�me sans que je renomme mon Datacenter?

**Comment by chambess** [comment]
J'ai créé le lien symbolique /var/lib/graphite/whisper/vmw/r?gion_alsace --> region_alsace mais j'ai toujours l'erreur d'initialisation des dashboard.
J'ai tenté un redémarrage des services/du serveur et toujours l'erreur...

Envoyé de mon iPhone

**Comment by rschitz** [comment]
ouai normal c'est l'initialisation de la liste qui pose probleme...
ya peut etre moyen de filtrer dans grafana, je vais essayer ca.

**Comment by chambess** [comment]
As-tu des news par rapport à ce problème?

**Comment by rschitz** [comment]
Oui, ca va etre plus simple de gerer ca coté script en remplacant les caracteres speciaux. Je reviens vers toi rapidement.

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/issues/89
