### ISSUE TITLE
VMware VSAN NAA Latency dashboard for T10 devices ?

### ISSUE THREAD

**Issue by tsugliani** [sexibytes/sexigraf#65]
Hi gents,

I've recently acquired a small Intel NUC homelab to play with VSAN 6.2 AF and it seems the dashboard for NAA latency doesn't take into account T10 devices.

![screenshot 2016-04-09 15 26 56](https://cloud.githubusercontent.com/assets/146306/14424443/5b0c8b12-ffe1-11e5-85a0-4b4e87a3a1fc.png)

Any plans to support this ?

Regards,

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/b9e997b0a8561c2534b1b43b7f3404a7d4174997#diff-1b6281a1bbcc56c7dca03950efd01d1b

**Comment by rschitz** [comment]
![image](https://cloud.githubusercontent.com/assets/8385646/14621369/7bdbf90e-05c2-11e6-8fb1-ea6c2bd4b316.png)
