### ISSUE TITLE
Use of uninitialized value $count in numeric lt (<) at /root/ViPullStatistics.pl line 129

### ISSUE THREAD

**Issue by goebelmeier** [sexibytes/sexigraf#76]
Hi there,

i've just installed a fresh sexigraf instance and provided vCenter credentials for a read-only user. Now i see the following loglines in /var/log/sexigraf/ViPullStatistics.log:
`[2016/05/19 08:50:05] /root/ViPullStatistics.pl line129 - WARN Use of uninitialized value $count in numeric lt (<) at /root/ViPullStatistics.pl line 129.`

Any ideas?

**Comment by rschitz** [comment]
Do you have any empty cluster?

**Comment by goebelmeier** [comment]
All 5 clusters have hosts and VMs inside. So there's no empty cluster.

**Comment by rschitz** [comment]
i get it we mess with the $count variable.
could you try to replace `my $count;` by `my $count = 0;` at line 127

**Comment by goebelmeier** [comment]
Thank you. The errors are gone now, but unfortunately we don't get any data points. Is there any way to turn on detailed debugging?

**Comment by sexibytes** [comment]
Any at all ?

**Comment by goebelmeier** [comment]
I do see the datapoints for the local system on the Home dashboard, but for example VMware Cluster FullStats is showing "no datapoints found"

**Comment by rschitz** [comment]
could you check in /var/lib/graphite/whisper/vmw/ if there is any folders and files there?

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/bdd02a0faa8d9aed51029e6188cb01b74b404325
