### ISSUE TITLE
Add vSphere "ready" metric per vm

### ISSUE THREAD

**Issue by rschitz** [sexibytes/sexigraf#79]
https://twitter.com/miquelmariano/status/734786855707643904

**Comment by rschitz** [comment]
![vmware_multi_cluster_top_n_vm_cpuready](https://cloud.githubusercontent.com/assets/8385646/19119608/9e02bf5c-8b20-11e6-84a5-521c1208ffb3.png)

**Comment by millardjk** [comment]
Co-stop (CSTP) would be a good one to add as well.

**Comment by rschitz** [comment]
Actually i got something even better, stay tuned ;)

**Comment by Wicaeed** [comment]
+1

**Comment by miquelMariano** [comment]
Hi guys. The new version not still ready for beta testers?? 😜😜

I'm ansxious to try these features

Good job!!!!

**Comment by rschitz** [comment]
Hi Miquel, thanks a lot for your support, it means a lot to us.
No beta test yet but it won't be long until we release the next update, stay tuned!
