### ISSUE TITLE
No ESX metrics

### ISSUE THREAD

**Issue by avinchakov** [sexibytes/sexigraf#85]
I see the empty dashboards for ESX.
```
ls -la /var/lib/graphite/whisper/
total 24
drwxr-xr-x 6 _graphite _graphite 4096 Jul 22 06:45 .
drwxr-xr-x 3 _graphite _graphite 4096 Jul 29 07:17 ..
drwxr-xr-x 3 _graphite _graphite 4096 May 12 23:33 carbon
drwxr-xr-x 3 _graphite _graphite 4096 May 12 23:33 collectd
drwxr-xr-x 3 _graphite _graphite 4096 Jul 22 06:42 vi
drwxr-xr-x 3 _graphite _graphite 4096 Jul 22 06:45 vmw
```

There is no **esx.** node!
But for dashboards is needed series like "target": "**esx**.$vcenter.$datacentre.$esx.quickstats.cpu.effective",

**Comment by avinchakov** [comment]
But VMware Cluster Multi ESX LiteStats is very uninformative(

**Comment by vmdude** [comment]
This one is for cluster indeed.
You have issue with this dashboard only ?

**Comment by avinchakov** [comment]
Also problems with VMware_ESX_FullStats of course. Thank you.

**Comment by vmdude** [comment]
The VMware_ESX_FullStats is for standalone server, so that should be "normal".
For the VMware Cluster Multi ESX LiteStats dashboard, did you try to change selected vcenter/datacentre/cluster/esx in the navigation bar ?
Do you have issue on all your objects ?

**Comment by avinchakov** [comment]
VMware Cluster Multi ESX LiteStats is working. Lack of metrics for IO of ESX or VM
