### ISSUE TITLE
enable Grafana "starred" dashboards

### ISSUE THREAD

**Issue by millardjk** [sexibytes/sexigraf#94]
The subject says it all. It appears that the "star" function of Grafana has been deliberately suppressed, making it impossible to star--and then filter on starred--dashboards. Lots of great dashboards in the product, but many of them won't get used on a day-to-day (hour-to-hour?) basis, and hiding the less-used with the star-filter would be awesome.

**Comment by rschitz** [comment]
It is still there but not for json files, try to save one as a copy and star it, you'll see it working
