### ISSUE TITLE
VSAN Congestion inconsistent between Multi VSAN Monitor & VSAN Monitor

### ISSUE THREAD

**Issue by millardjk** [sexibytes/sexigraf#95]
I've got a couple of clusters that I'm doing stress-testing on, and I'm able to get the VSAN Health to flag cluster congestion. I can see that happening in the Multi VSAN Monitor, along with lots of IOPS, but when switching to the VSAN Monitor, the Congestion metric for each host is flatline zero while other indicators like IOPS are still nice & high.

**Comment by rschitz** [comment]
Hi, did you try to switch between layers?

**Comment by millardjk** [comment]
Switching layers does make a difference (I didn't even think of that), and it's interesting that <disks> shows one host with congestion while <owner> shows a different one.

**Comment by rschitz** [comment]
Have a look here if you need a better understanding of each layer : http://www.sexigraf.fr/vsan-sexipanels/ And thanks for your support!
