### ISSUE TITLE
Issue with parenthesis in clusternames?

### ISSUE THREAD

**Issue by mikkelandreasen** [sexibytes/sexigraf#98]
Hi,
Just installed the latest Sexigraf, and it's pulling all expected data from 3 of our 6 clusters. The configured user has read only rights across all of them, and the only difference I can see is 3 of them have parenthesis in the clusternames.
It may not be a best practice, but that's what we've got :-/

**Comment by rschitz** [comment]
Hi, could you look at the VI log files to confirm?

**Comment by mikkelandreasen** [comment]
Would love to - where do I find them?

**Comment by sexibytes** [comment]
in the admin dashboard

**Comment by mikkelandreasen** [comment]
`[2016/11/22 13:31:57] /root/getInventory.pl line177 - [INFO] Start processing vCenter server.domain.tld
[2016/11/22 13:32:01] /root/getInventory.pl line133 - [INFO] Successfully retrieve 654 VM for vCenter server server.domain.tld in 4s
[2016/11/22 13:32:01] /root/getInventory.pl line180 - [INFO] End processing vCenter server.domain.tld
[2016/11/22 13:43:22] /root/getInventory.pl line177 - [INFO] Start processing vCenter server.domain.tld
[2016/11/22 13:43:26] /root/getInventory.pl line133 - [INFO] Successfully retrieve 654 VM for vCenter server server.domain.tld in 4s
[2016/11/22 13:43:26] /root/getInventory.pl line180 - [INFO] End processing vCenter server.domain.tld`

and

`[2016/11/22 16:15:01] /root/ViPullStatistics.pl line60 - [INFO] Start processing vCenter server.domain.tld
[2016/11/22 16:15:01] /root/ViPullStatistics.pl line82 - [INFO] Login to vCenter server.domain.tld
[2016/11/22 16:15:01] /root/ViPullStatistics.pl line96 - [INFO] vCenter server.domain.tld session file saved
[2016/11/22 16:15:01] /root/ViPullStatistics.pl line145 - [INFO] Processing vCenter server.domain.tld datacenters
[2016/11/22 16:15:01] /root/ViPullStatistics.pl line152 - [INFO] Processing vCenter server.domain.tld clusters in datacenter datacenter1
[2016/11/22 16:15:22] /root/ViPullStatistics.pl line366 - [INFO] Processing vCenter server.domain.tld standalone hosts in datacenter datacenter1
[2016/11/22 16:15:22] /root/ViPullStatistics.pl line477 - [INFO] End processing vCenter server.domain.tld
[2016/11/22 16:20:01] /root/ViPullStatistics.pl line60 - [INFO] Start processing vCenter server.domain.tld
[2016/11/22 16:20:01] /root/ViPullStatistics.pl line82 - [INFO] Login to vCenter server.domain.tld
[2016/11/22 16:20:02] /root/ViPullStatistics.pl line96 - [INFO] vCenter server.domain.tld session file saved
[2016/11/22 16:20:02] /root/ViPullStatistics.pl line145 - [INFO] Processing vCenter server.domain.tld datacenters
[2016/11/22 16:20:02] /root/ViPullStatistics.pl line152 - [INFO] Processing vCenter server.domain.tld clusters in datacenter datacenter1`

Those are the logfiles I see, but I suspect those are not the correct ones

**Comment by sexibytes** [comment]
you should see the cluster name

**Comment by mikkelandreasen** [comment]
I’m only seeing this. Correct place?

 



 

 

 

Fra: sexibytes [mailto:notifications@github.com] 
Sendt: 22. november 2016 13:22
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

you should see the cluster name

**Comment by sexibytes** [comment]
could you check in /var/lib/graphite/whisper/vmw ?

**Comment by mikkelandreasen** [comment]
Got a lot of content from all six clusters

**Comment by mikkelandreasen** [comment]
copying one of the "cluster folders" with parenthesis to a name without paranthesis, it works fine. Must be a graphana issue

**Comment by sexibytes** [comment]
it's not the first one like that but does the name are correct on the folder structure ?

**Comment by mikkelandreasen** [comment]
yes - the names are correct. Spaces have been replaced by underscores. Paranthesis are showing as they do in the C# and web clients

**Comment by rschitz** [comment]
ok as expected

**Comment by mikkelandreasen** [comment]
can I do anything to make it work?

**Comment by mikkelandreasen** [comment]
Made som symlinks from the directories with parenthesis in them - apears to be working

**Comment by rschitz** [comment]
That's an option yes

**Comment by mikkelandreasen** [comment]
The original clusters are still showing in Sexigraf,but empty. As I've deployed this for testing purposes it's OK for now, but it would be nice to not have to do it.
Anyways - I applaud you for the awesome product. Free. Supported. Works. Great!

**Comment by rschitz** [comment]
Would it be ok to replace () for _ ?
Thanks for your support!

**Comment by mikkelandreasen** [comment]
Yes – that would be perfect

 

Fra: Raphaël SCHITZ [mailto:notifications@github.com] 
Sendt: 22. november 2016 15:29
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

Would it be ok to replace () for _ ?
Thanks for your support!

**Comment by rschitz** [comment]
https://github.com/sexibytes/sexigraf/commit/cf87cd2536a447e878a90392d008c953e8c298f0#diff-935b03a0c3ffb068872406e170fad859

**Comment by rschitz** [comment]
please test this file https://raw.githubusercontent.com/sexibytes/sexigraf/dev/root/ViPullStatistics.pl

**Comment by mikkelandreasen** [comment]
Hi,

 

Just deployed a new Sexigraf and applied the file. Now it replaces all parentheses with underscores. I still see the non-working entries alongside them.



 

Fra: Raphaël SCHITZ [mailto:notifications@github.com] 
Sendt: 6. april 2017 12:50
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

please test this file https://raw.githubusercontent.com/sexibytes/sexigraf/dev/root/ViPullStatistics.pl

**Comment by rschitz** [comment]
Did you enabled VSAN polling ?

**Comment by mikkelandreasen** [comment]
No – we have no vSan as of yet (fingers crossed)

 

One thing I did notice – when selecting “all clusters” I get no data, as it still includes the clusters with parentheses

 

Fra: Raphaël SCHITZ [mailto:notifications@github.com] 
Sendt: 6. april 2017 13:19
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

Did you enabled VSAN polling ?

**Comment by sexibytes** [comment]
Did you replaced the file before or after addind the vcenter in the credential store?

**Comment by mikkelandreasen** [comment]
Ah… after… That would explain it

 

Fra: sexibytes [mailto:notifications@github.com] 
Sendt: 6. april 2017 13:52
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

Did you replaced the file before or after addind the vcenter in the credential store?

**Comment by rschitz** [comment]
Please wipe the /var/lib/graphite/whisper/v* folders and wait :)

**Comment by mikkelandreasen** [comment]
Done – waiting 😊

 

Fra: Raphaël SCHITZ [mailto:notifications@github.com] 
Sendt: 6. april 2017 14:00
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

Please wipe the /var/lib/graphite/whisper/v* folders and wait :)

**Comment by rschitz** [comment]
did it worked?

**Comment by mikkelandreasen** [comment]
Sorry – yes it did work 😊

 

Fra: Raphaël SCHITZ [mailto:notifications@github.com] 
Sendt: 7. april 2017 07:03
Til: sexibytes/sexigraf <sexigraf@noreply.github.com>
Cc: Mikkel Andreasen <man@ha.gl>; Author <author@noreply.github.com>
Emne: Re: [sexibytes/sexigraf] Issue with parenthesis in clusternames? (#98)

 

did it worked?
